// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertDays implements pgx.CopyFromSource.
type iteratorForInsertDays struct {
	rows                 []InsertDaysParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertDays) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertDays) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Date,
		r.rows[0].IsOffDay,
		r.rows[0].Name,
	}, nil
}

func (r iteratorForInsertDays) Err() error {
	return nil
}

func (q *Queries) InsertDays(ctx context.Context, arg []InsertDaysParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"holiday_days"}, []string{"date", "is_off_day", "name"}, &iteratorForInsertDays{rows: arg})
}
