// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const deleteYear = `-- name: DeleteYear :exec
DELETE FROM holiday_days
WHERE date >= make_date($1::int, 1, 1) AND date < make_date($1::int + 1, 1, 1)
`

func (q *Queries) DeleteYear(ctx context.Context, year int32) error {
	_, err := q.db.Exec(ctx, deleteYear, year)
	return err
}

const findDay = `-- name: FindDay :one
SELECT date, is_off_day, name FROM holiday_days WHERE date = $1
`

// 节假日安排里这一天的那一行。
func (q *Queries) FindDay(ctx context.Context, date time.Time) (HolidayDay, error) {
	row := q.db.QueryRow(ctx, findDay, date)
	var i HolidayDay
	err := row.Scan(&i.Date, &i.IsOffDay, &i.Name)
	return i, err
}

const hasYear = `-- name: HasYear :one
SELECT EXISTS (
  SELECT 1 FROM holiday_days
  WHERE date >= make_date($1::int, 1, 1) AND date < make_date($1::int + 1, 1, 1)
)
`

// 库里有没有这一年的安排。按年份写成日期范围，走得上 date 主键的索引。
func (q *Queries) HasYear(ctx context.Context, year int32) (bool, error) {
	row := q.db.QueryRow(ctx, hasYear, year)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

type InsertDaysParams struct {
	Date     time.Time
	IsOffDay bool
	Name     string
}
