// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"
)

const deleteHolidayDaysByYearPrefix = `-- name: DeleteHolidayDaysByYearPrefix :exec
DELETE FROM holiday_days WHERE date LIKE $1
`

func (q *Queries) DeleteHolidayDaysByYearPrefix(ctx context.Context, date string) error {
	_, err := q.db.Exec(ctx, deleteHolidayDaysByYearPrefix, date)
	return err
}

const getHolidayDayByDate = `-- name: GetHolidayDayByDate :one
SELECT name, date, is_off_day FROM holiday_days WHERE date = $1
`

type GetHolidayDayByDateRow struct {
	Name     string
	Date     string
	IsOffDay bool
}

func (q *Queries) GetHolidayDayByDate(ctx context.Context, date string) (GetHolidayDayByDateRow, error) {
	row := q.db.QueryRow(ctx, getHolidayDayByDate, date)
	var i GetHolidayDayByDateRow
	err := row.Scan(&i.Name, &i.Date, &i.IsOffDay)
	return i, err
}

const insertHolidayDays = `-- name: InsertHolidayDays :exec
INSERT INTO holiday_days (name, date, is_off_day, created_at, updated_at)
SELECT unnest($1::text[]), unnest($2::text[]), unnest($3::boolean[]), now(), now()
`

type InsertHolidayDaysParams struct {
	Names     []string
	Dates     []string
	IsOffDays []bool
}

// 单条语句插入整年的数据。三个 unnest 并排展开，比拼多行 VALUES 省事，
// 而且空数组自然插 0 行——2027 年安排还没发布时远程返回的就是空列表。
func (q *Queries) InsertHolidayDays(ctx context.Context, arg InsertHolidayDaysParams) error {
	_, err := q.db.Exec(ctx, insertHolidayDays, arg.Names, arg.Dates, arg.IsOffDays)
	return err
}
