use jiff::Timestamp;
use jiff::civil::date;
use jiff_sqlx::ToSqlx;
use myapi::holiday::{china_date, query};

use crate::support::{Database, holiday_source, try_start, unreachable_url};

/// 启动时刷新节假日数据：数据源在 GitHub 上，偶尔连不上，库里已经有今年的安排就照常启动；
/// 连今年的都没有才拒绝启动，免得接口带着空表一直按周末规则回错误答案。
#[tokio::test]
async fn unreachable_source_blocks_startup_only_without_this_years_data() {
    let database = Database::start().await;
    let source = holiday_source(&unreachable_url().await);

    let pool = database.pool();
    let error = try_start(pool.clone(), source.clone())
        .await
        .err()
        .expect("没有今年的安排时应当拒绝启动");
    assert!(format!("{error:#}").contains("拉取"), "{error:#}");

    let new_year = china_date(Timestamp::now()).first_of_year();
    sqlx::query("INSERT INTO holiday_days (date, is_off_day, name) VALUES ($1, true, '元旦')")
        .bind(new_year.to_sqlx())
        .execute(&pool)
        .await
        .expect("应当插得进去");
    let server = try_start(pool.clone(), source)
        .await
        .expect("有今年的安排时应当照常启动");
    assert_eq!(
        query(&pool, new_year).await.expect("应当查得到").name,
        "元旦"
    );

    server.shutdown().await.expect("应用应当正常关停");
    pool.close().await;
}

/// 已经部署过的库上是 TypeScript 版的表结构与 drizzle 的迁移登记：数据原样保留，登记删掉。
#[tokio::test]
async fn existing_database_is_migrated_in_place() {
    let database = Database::start().await;
    let pool = database.pool();
    for statement in [
        "CREATE SCHEMA drizzle",
        "CREATE TABLE drizzle.__drizzle_migrations (id serial PRIMARY KEY, hash text NOT NULL)",
        r#"CREATE TABLE "holiday_days" (
            "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "name" text NOT NULL,
            "date" text NOT NULL,
            "is_off_day" boolean NOT NULL,
            "created_at" timestamp (3) with time zone DEFAULT now() NOT NULL,
            "updated_at" timestamp (3) with time zone DEFAULT now() NOT NULL
        )"#,
        r#"CREATE UNIQUE INDEX "holiday_days_date_key" ON "holiday_days" USING btree ("date")"#,
        "INSERT INTO holiday_days (name, date, is_off_day) VALUES ('元旦', '2025-01-01', true), ('春节', '2025-01-26', false)",
    ] {
        sqlx::query(statement)
            .execute(&pool)
            .await
            .expect("旧的表结构应当建得出来");
    }

    // 数据源里只有 2026 年：2025 年的数据只能来自旧表
    let source = crate::support::FakeSource::start().await;
    let server = try_start(pool.clone(), holiday_source(source.url()))
        .await
        .expect("应用应当起得来");

    let day = query(&pool, date(2025, 1, 26)).await.expect("应当查得到");
    assert_eq!((day.is_off_day, day.name.as_str()), (false, "春节"));
    let columns: Vec<String> = sqlx::query_scalar(
        "SELECT column_name::text FROM information_schema.columns WHERE table_name = 'holiday_days' ORDER BY column_name",
    )
    .fetch_all(&pool)
    .await
    .expect("应当查得到列");
    assert_eq!(columns, ["date", "is_off_day", "name"]);
    let drizzle: bool =
        sqlx::query_scalar("SELECT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'drizzle')")
            .fetch_one(&pool)
            .await
            .expect("应当查得到 schema");
    assert!(!drizzle, "drizzle 的迁移登记应当删掉");

    server.shutdown().await.expect("应用应当正常关停");
    pool.close().await;
}
