// Code generated by ent, DO NOT EDIT.

package codexresponselog

import (
	"myapi/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLTE(FieldID, id))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldUserAgent, v))
}

// ClientIP applies equality check predicate on the "client_ip" field. It's identical to ClientIPEQ.
func ClientIP(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldClientIP, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldInputTokens, v))
}

// CachedInputTokens applies equality check predicate on the "cached_input_tokens" field. It's identical to CachedInputTokensEQ.
func CachedInputTokens(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldCachedInputTokens, v))
}

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldOutputTokens, v))
}

// CacheRate applies equality check predicate on the "cache_rate" field. It's identical to CacheRateEQ.
func CacheRate(v float64) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldCacheRate, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldDurationMs, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldAccountID, v))
}

// AccountName applies equality check predicate on the "account_name" field. It's identical to AccountNameEQ.
func AccountName(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldAccountName, v))
}

// IsSse applies equality check predicate on the "is_sse" field. It's identical to IsSseEQ.
func IsSse(v bool) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldIsSse, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldCreatedAt, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldContainsFold(FieldUserAgent, v))
}

// ClientIPEQ applies the EQ predicate on the "client_ip" field.
func ClientIPEQ(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldClientIP, v))
}

// ClientIPNEQ applies the NEQ predicate on the "client_ip" field.
func ClientIPNEQ(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNEQ(FieldClientIP, v))
}

// ClientIPIn applies the In predicate on the "client_ip" field.
func ClientIPIn(vs ...string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldIn(FieldClientIP, vs...))
}

// ClientIPNotIn applies the NotIn predicate on the "client_ip" field.
func ClientIPNotIn(vs ...string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNotIn(FieldClientIP, vs...))
}

// ClientIPGT applies the GT predicate on the "client_ip" field.
func ClientIPGT(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGT(FieldClientIP, v))
}

// ClientIPGTE applies the GTE predicate on the "client_ip" field.
func ClientIPGTE(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGTE(FieldClientIP, v))
}

// ClientIPLT applies the LT predicate on the "client_ip" field.
func ClientIPLT(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLT(FieldClientIP, v))
}

// ClientIPLTE applies the LTE predicate on the "client_ip" field.
func ClientIPLTE(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLTE(FieldClientIP, v))
}

// ClientIPContains applies the Contains predicate on the "client_ip" field.
func ClientIPContains(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldContains(FieldClientIP, v))
}

// ClientIPHasPrefix applies the HasPrefix predicate on the "client_ip" field.
func ClientIPHasPrefix(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldHasPrefix(FieldClientIP, v))
}

// ClientIPHasSuffix applies the HasSuffix predicate on the "client_ip" field.
func ClientIPHasSuffix(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldHasSuffix(FieldClientIP, v))
}

// ClientIPEqualFold applies the EqualFold predicate on the "client_ip" field.
func ClientIPEqualFold(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEqualFold(FieldClientIP, v))
}

// ClientIPContainsFold applies the ContainsFold predicate on the "client_ip" field.
func ClientIPContainsFold(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldContainsFold(FieldClientIP, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLTE(FieldInputTokens, v))
}

// CachedInputTokensEQ applies the EQ predicate on the "cached_input_tokens" field.
func CachedInputTokensEQ(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldCachedInputTokens, v))
}

// CachedInputTokensNEQ applies the NEQ predicate on the "cached_input_tokens" field.
func CachedInputTokensNEQ(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNEQ(FieldCachedInputTokens, v))
}

// CachedInputTokensIn applies the In predicate on the "cached_input_tokens" field.
func CachedInputTokensIn(vs ...int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldIn(FieldCachedInputTokens, vs...))
}

// CachedInputTokensNotIn applies the NotIn predicate on the "cached_input_tokens" field.
func CachedInputTokensNotIn(vs ...int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNotIn(FieldCachedInputTokens, vs...))
}

// CachedInputTokensGT applies the GT predicate on the "cached_input_tokens" field.
func CachedInputTokensGT(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGT(FieldCachedInputTokens, v))
}

// CachedInputTokensGTE applies the GTE predicate on the "cached_input_tokens" field.
func CachedInputTokensGTE(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGTE(FieldCachedInputTokens, v))
}

// CachedInputTokensLT applies the LT predicate on the "cached_input_tokens" field.
func CachedInputTokensLT(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLT(FieldCachedInputTokens, v))
}

// CachedInputTokensLTE applies the LTE predicate on the "cached_input_tokens" field.
func CachedInputTokensLTE(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLTE(FieldCachedInputTokens, v))
}

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldOutputTokens, v))
}

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNEQ(FieldOutputTokens, v))
}

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldIn(FieldOutputTokens, vs...))
}

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNotIn(FieldOutputTokens, vs...))
}

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGT(FieldOutputTokens, v))
}

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGTE(FieldOutputTokens, v))
}

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLT(FieldOutputTokens, v))
}

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLTE(FieldOutputTokens, v))
}

// CacheRateEQ applies the EQ predicate on the "cache_rate" field.
func CacheRateEQ(v float64) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldCacheRate, v))
}

// CacheRateNEQ applies the NEQ predicate on the "cache_rate" field.
func CacheRateNEQ(v float64) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNEQ(FieldCacheRate, v))
}

// CacheRateIn applies the In predicate on the "cache_rate" field.
func CacheRateIn(vs ...float64) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldIn(FieldCacheRate, vs...))
}

// CacheRateNotIn applies the NotIn predicate on the "cache_rate" field.
func CacheRateNotIn(vs ...float64) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNotIn(FieldCacheRate, vs...))
}

// CacheRateGT applies the GT predicate on the "cache_rate" field.
func CacheRateGT(v float64) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGT(FieldCacheRate, v))
}

// CacheRateGTE applies the GTE predicate on the "cache_rate" field.
func CacheRateGTE(v float64) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGTE(FieldCacheRate, v))
}

// CacheRateLT applies the LT predicate on the "cache_rate" field.
func CacheRateLT(v float64) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLT(FieldCacheRate, v))
}

// CacheRateLTE applies the LTE predicate on the "cache_rate" field.
func CacheRateLTE(v float64) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLTE(FieldCacheRate, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLTE(FieldDurationMs, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDContains applies the Contains predicate on the "account_id" field.
func AccountIDContains(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldContains(FieldAccountID, v))
}

// AccountIDHasPrefix applies the HasPrefix predicate on the "account_id" field.
func AccountIDHasPrefix(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldHasPrefix(FieldAccountID, v))
}

// AccountIDHasSuffix applies the HasSuffix predicate on the "account_id" field.
func AccountIDHasSuffix(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldHasSuffix(FieldAccountID, v))
}

// AccountIDEqualFold applies the EqualFold predicate on the "account_id" field.
func AccountIDEqualFold(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEqualFold(FieldAccountID, v))
}

// AccountIDContainsFold applies the ContainsFold predicate on the "account_id" field.
func AccountIDContainsFold(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldContainsFold(FieldAccountID, v))
}

// AccountNameEQ applies the EQ predicate on the "account_name" field.
func AccountNameEQ(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldAccountName, v))
}

// AccountNameNEQ applies the NEQ predicate on the "account_name" field.
func AccountNameNEQ(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNEQ(FieldAccountName, v))
}

// AccountNameIn applies the In predicate on the "account_name" field.
func AccountNameIn(vs ...string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldIn(FieldAccountName, vs...))
}

// AccountNameNotIn applies the NotIn predicate on the "account_name" field.
func AccountNameNotIn(vs ...string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNotIn(FieldAccountName, vs...))
}

// AccountNameGT applies the GT predicate on the "account_name" field.
func AccountNameGT(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGT(FieldAccountName, v))
}

// AccountNameGTE applies the GTE predicate on the "account_name" field.
func AccountNameGTE(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGTE(FieldAccountName, v))
}

// AccountNameLT applies the LT predicate on the "account_name" field.
func AccountNameLT(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLT(FieldAccountName, v))
}

// AccountNameLTE applies the LTE predicate on the "account_name" field.
func AccountNameLTE(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLTE(FieldAccountName, v))
}

// AccountNameContains applies the Contains predicate on the "account_name" field.
func AccountNameContains(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldContains(FieldAccountName, v))
}

// AccountNameHasPrefix applies the HasPrefix predicate on the "account_name" field.
func AccountNameHasPrefix(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldHasPrefix(FieldAccountName, v))
}

// AccountNameHasSuffix applies the HasSuffix predicate on the "account_name" field.
func AccountNameHasSuffix(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldHasSuffix(FieldAccountName, v))
}

// AccountNameEqualFold applies the EqualFold predicate on the "account_name" field.
func AccountNameEqualFold(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEqualFold(FieldAccountName, v))
}

// AccountNameContainsFold applies the ContainsFold predicate on the "account_name" field.
func AccountNameContainsFold(v string) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldContainsFold(FieldAccountName, v))
}

// IsSseEQ applies the EQ predicate on the "is_sse" field.
func IsSseEQ(v bool) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldIsSse, v))
}

// IsSseNEQ applies the NEQ predicate on the "is_sse" field.
func IsSseNEQ(v bool) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNEQ(FieldIsSse, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CodexResponseLog) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CodexResponseLog) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CodexResponseLog) predicate.CodexResponseLog {
	return predicate.CodexResponseLog(sql.NotPredicates(p))
}
