-- 基线：拆仓（图库与账号移到 eh-pwa）时重建，只剩节假日一张表。由 drizzle-kit 生成后改成幂等的形式：
-- 在已经建过 holiday_days 的库上执行时什么也不改，只由迁移器登记为已执行；在空库上则建出同样的结构。
-- 同目录的 meta/0000_snapshot.json 保持生成原样，后续迁移照常生成。
CREATE TABLE IF NOT EXISTS "holiday_days" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "holiday_days_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"date" text NOT NULL,
	"is_off_day" boolean NOT NULL,
	"created_at" timestamp (3) with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp (3) with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "holiday_days_date_key" ON "holiday_days" USING btree ("date");
