-- 基线：Kotlin 版时期人工建出的表结构，逐字沿用。
-- 写成 IF NOT EXISTS 的幂等形式：在已有这些表的库上执行时什么也不改，只由迁移器登记为已执行；在空库上则建出同样的结构。
-- 这个文件不是 drizzle-kit 生成的（生成的版本不幂等），同目录的 meta/0000_snapshot.json 仍描述同一份结构，后续迁移照常生成。
CREATE TABLE IF NOT EXISTS users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT        NOT NULL,
    password_hash TEXT        NOT NULL,
    created_at    timestamptz NOT NULL,
    updated_at    timestamptz NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS users_username_key ON users (username);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS eh_credentials
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    member_id     TEXT        NOT NULL,
    cookie        TEXT        NOT NULL,
    has_ex_access BOOLEAN     NOT NULL,
    created_at    timestamptz NOT NULL,
    updated_at    timestamptz NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS eh_credentials_user_id_key ON eh_credentials (user_id);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS eh_reading_progress
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    gid        BIGINT      NOT NULL,
    token      TEXT        NOT NULL,
    page       INTEGER     NOT NULL,
    writer     TEXT        NOT NULL,
    seq        INTEGER     NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS eh_reading_progress_user_gid_key ON eh_reading_progress (user_id, gid);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS eh_reading_progress_user_recent_idx ON eh_reading_progress (user_id, updated_at DESC, gid DESC);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS eh_preferences
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    categories      TEXT[]      NOT NULL DEFAULT '{}',
    reader_interval INTEGER     NOT NULL DEFAULT 5 CHECK (reader_interval BETWEEN 1 AND 20),
    search_history  TEXT[]      NOT NULL DEFAULT '{}' CHECK (CARDINALITY(search_history) <= 10),
    created_at      timestamptz NOT NULL,
    updated_at      timestamptz NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS eh_preferences_user_id_key ON eh_preferences (user_id);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS holiday_days
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT        NOT NULL,
    date       TEXT        NOT NULL,
    is_off_day BOOLEAN     NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS holiday_days_date_key ON holiday_days (date);
