// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"
)

type EhCredential struct {
	ID          int64
	UserID      int64
	MemberID    string
	Cookie      string
	HasExAccess bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type EhPreference struct {
	ID             int64
	UserID         int64
	Categories     []string
	ReaderInterval int32
	SearchHistory  []string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type EhReadingProgress struct {
	ID        int64
	UserID    int64
	Gid       int64
	Token     string
	Page      int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type HolidayDay struct {
	ID        int64
	Name      string
	Date      string
	IsOffDay  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
