// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"
)

const clearEhSearchHistory = `-- name: ClearEhSearchHistory :exec
UPDATE eh_preferences SET search_history = '{}', updated_at = now() WHERE user_id = $1
`

func (q *Queries) ClearEhSearchHistory(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, clearEhSearchHistory, userID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, created_at, updated_at)
VALUES ($1, $2, now(), now())
RETURNING id, username, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEhCredential = `-- name: DeleteEhCredential :exec
DELETE FROM eh_credentials WHERE user_id = $1
`

func (q *Queries) DeleteEhCredential(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteEhCredential, userID)
	return err
}

const deleteHolidayDaysByYearPrefix = `-- name: DeleteHolidayDaysByYearPrefix :exec
DELETE FROM holiday_days WHERE date LIKE $1
`

func (q *Queries) DeleteHolidayDaysByYearPrefix(ctx context.Context, date string) error {
	_, err := q.db.Exec(ctx, deleteHolidayDaysByYearPrefix, date)
	return err
}

const getEhCredential = `-- name: GetEhCredential :one
SELECT member_id, cookie, has_ex_access FROM eh_credentials WHERE user_id = $1
`

type GetEhCredentialRow struct {
	MemberID    string
	Cookie      string
	HasExAccess bool
}

func (q *Queries) GetEhCredential(ctx context.Context, userID int64) (GetEhCredentialRow, error) {
	row := q.db.QueryRow(ctx, getEhCredential, userID)
	var i GetEhCredentialRow
	err := row.Scan(&i.MemberID, &i.Cookie, &i.HasExAccess)
	return i, err
}

const getEhPreferences = `-- name: GetEhPreferences :one
SELECT categories, reader_interval FROM eh_preferences WHERE user_id = $1
`

type GetEhPreferencesRow struct {
	Categories     []string
	ReaderInterval int32
}

func (q *Queries) GetEhPreferences(ctx context.Context, userID int64) (GetEhPreferencesRow, error) {
	row := q.db.QueryRow(ctx, getEhPreferences, userID)
	var i GetEhPreferencesRow
	err := row.Scan(&i.Categories, &i.ReaderInterval)
	return i, err
}

const getEhSearchHistory = `-- name: GetEhSearchHistory :one
SELECT search_history FROM eh_preferences WHERE user_id = $1
`

func (q *Queries) GetEhSearchHistory(ctx context.Context, userID int64) ([]string, error) {
	row := q.db.QueryRow(ctx, getEhSearchHistory, userID)
	var search_history []string
	err := row.Scan(&search_history)
	return search_history, err
}

const getHolidayDayByDate = `-- name: GetHolidayDayByDate :one
SELECT name, date, is_off_day FROM holiday_days WHERE date = $1
`

type GetHolidayDayByDateRow struct {
	Name     string
	Date     string
	IsOffDay bool
}

func (q *Queries) GetHolidayDayByDate(ctx context.Context, date string) (GetHolidayDayByDateRow, error) {
	row := q.db.QueryRow(ctx, getHolidayDayByDate, date)
	var i GetHolidayDayByDateRow
	err := row.Scan(&i.Name, &i.Date, &i.IsOffDay)
	return i, err
}

const getReadingProgress = `-- name: GetReadingProgress :one
SELECT page FROM eh_reading_progress WHERE user_id = $1 AND gid = $2
`

type GetReadingProgressParams struct {
	UserID int64
	Gid    int64
}

func (q *Queries) GetReadingProgress(ctx context.Context, arg GetReadingProgressParams) (int32, error) {
	row := q.db.QueryRow(ctx, getReadingProgress, arg.UserID, arg.Gid)
	var page int32
	err := row.Scan(&page)
	return page, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHolidayDays = `-- name: InsertHolidayDays :exec
INSERT INTO holiday_days (name, date, is_off_day, created_at, updated_at)
SELECT unnest($1::text[]), unnest($2::text[]), unnest($3::boolean[]), now(), now()
`

type InsertHolidayDaysParams struct {
	Names     []string
	Dates     []string
	IsOffDays []bool
}

// 单条语句插入整年的数据。三个 unnest 并排展开，比拼多行 VALUES 省事，
// 而且空数组自然插 0 行——2027 年安排还没发布时远程返回的就是空列表。
func (q *Queries) InsertHolidayDays(ctx context.Context, arg InsertHolidayDaysParams) error {
	_, err := q.db.Exec(ctx, insertHolidayDays, arg.Names, arg.Dates, arg.IsOffDays)
	return err
}

const recordEhSearch = `-- name: RecordEhSearch :one
INSERT INTO eh_preferences (user_id, search_history, created_at, updated_at)
VALUES ($1, ARRAY[$2::text], now(), now())
ON CONFLICT (user_id) DO UPDATE
SET search_history = (ARRAY[$2::text] || array_remove(eh_preferences.search_history, $2::text))[1:10],
    updated_at = now()
RETURNING search_history
`

type RecordEhSearchParams struct {
	UserID  int64
	Keyword string
}

// 在同一条语句里去重并截取最近十条；并发提交不会用客户端的旧数组覆盖其他设备。
func (q *Queries) RecordEhSearch(ctx context.Context, arg RecordEhSearchParams) ([]string, error) {
	row := q.db.QueryRow(ctx, recordEhSearch, arg.UserID, arg.Keyword)
	var search_history []string
	err := row.Scan(&search_history)
	return search_history, err
}

const removeEhSearch = `-- name: RemoveEhSearch :one
UPDATE eh_preferences
SET search_history = array_remove(search_history, $1::text), updated_at = now()
WHERE user_id = $2
RETURNING search_history
`

type RemoveEhSearchParams struct {
	Keyword string
	UserID  int64
}

func (q *Queries) RemoveEhSearch(ctx context.Context, arg RemoveEhSearchParams) ([]string, error) {
	row := q.db.QueryRow(ctx, removeEhSearch, arg.Keyword, arg.UserID)
	var search_history []string
	err := row.Scan(&search_history)
	return search_history, err
}

const saveEhCategories = `-- name: SaveEhCategories :exec
INSERT INTO eh_preferences (user_id, categories, created_at, updated_at)
VALUES ($1, $2, now(), now())
ON CONFLICT (user_id) DO UPDATE
SET categories = excluded.categories, updated_at = now()
`

type SaveEhCategoriesParams struct {
	UserID     int64
	Categories []string
}

func (q *Queries) SaveEhCategories(ctx context.Context, arg SaveEhCategoriesParams) error {
	_, err := q.db.Exec(ctx, saveEhCategories, arg.UserID, arg.Categories)
	return err
}

const saveEhReaderInterval = `-- name: SaveEhReaderInterval :exec
INSERT INTO eh_preferences (user_id, reader_interval, created_at, updated_at)
VALUES ($1, $2, now(), now())
ON CONFLICT (user_id) DO UPDATE
SET reader_interval = excluded.reader_interval, updated_at = now()
`

type SaveEhReaderIntervalParams struct {
	UserID         int64
	ReaderInterval int32
}

func (q *Queries) SaveEhReaderInterval(ctx context.Context, arg SaveEhReaderIntervalParams) error {
	_, err := q.db.Exec(ctx, saveEhReaderInterval, arg.UserID, arg.ReaderInterval)
	return err
}

const upsertEhCredential = `-- name: UpsertEhCredential :exec
INSERT INTO eh_credentials (user_id, member_id, cookie, has_ex_access, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
ON CONFLICT (user_id) DO UPDATE
SET member_id = excluded.member_id,
    cookie = excluded.cookie,
    has_ex_access = excluded.has_ex_access,
    updated_at = now()
`

type UpsertEhCredentialParams struct {
	UserID      int64
	MemberID    string
	Cookie      string
	HasExAccess bool
}

func (q *Queries) UpsertEhCredential(ctx context.Context, arg UpsertEhCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertEhCredential,
		arg.UserID,
		arg.MemberID,
		arg.Cookie,
		arg.HasExAccess,
	)
	return err
}

const upsertReadingProgress = `-- name: UpsertReadingProgress :exec
INSERT INTO eh_reading_progress (user_id, gid, token, page, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
ON CONFLICT (user_id, gid) DO UPDATE
SET token = excluded.token,
    page = excluded.page,
    updated_at = now()
`

type UpsertReadingProgressParams struct {
	UserID int64
	Gid    int64
	Token  string
	Page   int32
}

func (q *Queries) UpsertReadingProgress(ctx context.Context, arg UpsertReadingProgressParams) error {
	_, err := q.db.Exec(ctx, upsertReadingProgress,
		arg.UserID,
		arg.Gid,
		arg.Token,
		arg.Page,
	)
	return err
}
