// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash, created_at, updated_at)
VALUES ($1, $2, now(), now())
RETURNING id, username, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEhCredential = `-- name: DeleteEhCredential :exec
DELETE FROM eh_credentials WHERE user_id = $1
`

func (q *Queries) DeleteEhCredential(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteEhCredential, userID)
	return err
}

const deleteHolidayDaysByYearPrefix = `-- name: DeleteHolidayDaysByYearPrefix :exec
DELETE FROM holiday_days WHERE date LIKE $1
`

func (q *Queries) DeleteHolidayDaysByYearPrefix(ctx context.Context, date string) error {
	_, err := q.db.Exec(ctx, deleteHolidayDaysByYearPrefix, date)
	return err
}

const getEhCredential = `-- name: GetEhCredential :one
SELECT member_id, cookie, has_ex_access FROM eh_credentials WHERE user_id = $1
`

type GetEhCredentialRow struct {
	MemberID    string
	Cookie      string
	HasExAccess bool
}

func (q *Queries) GetEhCredential(ctx context.Context, userID int64) (GetEhCredentialRow, error) {
	row := q.db.QueryRow(ctx, getEhCredential, userID)
	var i GetEhCredentialRow
	err := row.Scan(&i.MemberID, &i.Cookie, &i.HasExAccess)
	return i, err
}

const getHolidayDayByDate = `-- name: GetHolidayDayByDate :one
SELECT name, date, is_off_day FROM holiday_days WHERE date = $1
`

type GetHolidayDayByDateRow struct {
	Name     string
	Date     string
	IsOffDay bool
}

func (q *Queries) GetHolidayDayByDate(ctx context.Context, date string) (GetHolidayDayByDateRow, error) {
	row := q.db.QueryRow(ctx, getHolidayDayByDate, date)
	var i GetHolidayDayByDateRow
	err := row.Scan(&i.Name, &i.Date, &i.IsOffDay)
	return i, err
}

const getReadingProgress = `-- name: GetReadingProgress :one
SELECT page FROM eh_reading_progress WHERE user_id = $1 AND gid = $2
`

type GetReadingProgressParams struct {
	UserID int64
	Gid    int64
}

func (q *Queries) GetReadingProgress(ctx context.Context, arg GetReadingProgressParams) (int32, error) {
	row := q.db.QueryRow(ctx, getReadingProgress, arg.UserID, arg.Gid)
	var page int32
	err := row.Scan(&page)
	return page, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password_hash, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHolidayDays = `-- name: InsertHolidayDays :exec
INSERT INTO holiday_days (name, date, is_off_day, created_at, updated_at)
SELECT unnest($1::text[]), unnest($2::text[]), unnest($3::boolean[]), now(), now()
`

type InsertHolidayDaysParams struct {
	Names     []string
	Dates     []string
	IsOffDays []bool
}

// 单条语句插入整年的数据。三个 unnest 并排展开，比拼多行 VALUES 省事，
// 而且空数组自然插 0 行——2027 年安排还没发布时远程返回的就是空列表。
func (q *Queries) InsertHolidayDays(ctx context.Context, arg InsertHolidayDaysParams) error {
	_, err := q.db.Exec(ctx, insertHolidayDays, arg.Names, arg.Dates, arg.IsOffDays)
	return err
}

const upsertEhCredential = `-- name: UpsertEhCredential :exec
INSERT INTO eh_credentials (user_id, member_id, cookie, has_ex_access, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
ON CONFLICT (user_id) DO UPDATE
SET member_id = excluded.member_id,
    cookie = excluded.cookie,
    has_ex_access = excluded.has_ex_access,
    updated_at = now()
`

type UpsertEhCredentialParams struct {
	UserID      int64
	MemberID    string
	Cookie      string
	HasExAccess bool
}

func (q *Queries) UpsertEhCredential(ctx context.Context, arg UpsertEhCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertEhCredential,
		arg.UserID,
		arg.MemberID,
		arg.Cookie,
		arg.HasExAccess,
	)
	return err
}

const upsertReadingProgress = `-- name: UpsertReadingProgress :exec
INSERT INTO eh_reading_progress (user_id, gid, token, page, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
ON CONFLICT (user_id, gid) DO UPDATE
SET token = excluded.token,
    page = excluded.page,
    updated_at = now()
`

type UpsertReadingProgressParams struct {
	UserID int64
	Gid    int64
	Token  string
	Page   int32
}

func (q *Queries) UpsertReadingProgress(ctx context.Context, arg UpsertReadingProgressParams) error {
	_, err := q.db.Exec(ctx, upsertReadingProgress,
		arg.UserID,
		arg.Gid,
		arg.Token,
		arg.Page,
	)
	return err
}
