// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// HolidayDaysColumns holds the columns for the "holiday_days" table.
	HolidayDaysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "date", Type: field.TypeString, Unique: true},
		{Name: "is_off_day", Type: field.TypeBool},
	}
	// HolidayDaysTable holds the schema information for the "holiday_days" table.
	HolidayDaysTable = &schema.Table{
		Name:       "holiday_days",
		Columns:    HolidayDaysColumns,
		PrimaryKey: []*schema.Column{HolidayDaysColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		HolidayDaysTable,
	}
)

func init() {
}
