// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"github.com/kzw200015/myapi/internal/config"
	"github.com/kzw200015/myapi/internal/database"
	"github.com/kzw200015/myapi/internal/holiday"
	"github.com/kzw200015/myapi/internal/outbound"
	"github.com/kzw200015/myapi/internal/web"
)

// Injectors from wire.go:

// initApp 构造服务的全部部件；返回的 cleanup 按构造的逆序释放资源。
//
// 改了这里或构造函数的参数后重新生成 wire_gen.go：go tool wire ./internal/app。
func initApp(ctx context.Context, cfg config.Config) (*app, func(), error) {
	client := outbound.NewClient(cfg)
	source := holiday.NewSource(client, cfg)
	pool, cleanup, err := database.NewPool(ctx, cfg)
	if err != nil {
		return nil, nil, err
	}
	store := holiday.NewStore(pool)
	refresher := holiday.NewRefresher(source, store)
	service := holiday.NewService(store)
	echo := web.NewServer(pool, service)
	appApp := &app{
		refresher: refresher,
		server:    echo,
	}
	return appApp, func() {
		cleanup()
	}, nil
}
