// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"myapi/internal/ent/codexaccount"
	"myapi/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CodexAccountDelete is the builder for deleting a CodexAccount entity.
type CodexAccountDelete struct {
	config
	hooks    []Hook
	mutation *CodexAccountMutation
}

// Where appends a list predicates to the CodexAccountDelete builder.
func (_d *CodexAccountDelete) Where(ps ...predicate.CodexAccount) *CodexAccountDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CodexAccountDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CodexAccountDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CodexAccountDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(codexaccount.Table, sqlgraph.NewFieldSpec(codexaccount.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CodexAccountDeleteOne is the builder for deleting a single CodexAccount entity.
type CodexAccountDeleteOne struct {
	_d *CodexAccountDelete
}

// Where appends a list predicates to the CodexAccountDelete builder.
func (_d *CodexAccountDeleteOne) Where(ps ...predicate.CodexAccount) *CodexAccountDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CodexAccountDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{codexaccount.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CodexAccountDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
