// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"myapi/internal/ent/codexresponselog"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CodexResponseLogCreate is the builder for creating a CodexResponseLog entity.
type CodexResponseLogCreate struct {
	config
	mutation *CodexResponseLogMutation
	hooks    []Hook
}

// SetUserAgent sets the "user_agent" field.
func (_c *CodexResponseLogCreate) SetUserAgent(v string) *CodexResponseLogCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetClientIP sets the "client_ip" field.
func (_c *CodexResponseLogCreate) SetClientIP(v string) *CodexResponseLogCreate {
	_c.mutation.SetClientIP(v)
	return _c
}

// SetInputTokens sets the "input_tokens" field.
func (_c *CodexResponseLogCreate) SetInputTokens(v int) *CodexResponseLogCreate {
	_c.mutation.SetInputTokens(v)
	return _c
}

// SetCachedInputTokens sets the "cached_input_tokens" field.
func (_c *CodexResponseLogCreate) SetCachedInputTokens(v int) *CodexResponseLogCreate {
	_c.mutation.SetCachedInputTokens(v)
	return _c
}

// SetOutputTokens sets the "output_tokens" field.
func (_c *CodexResponseLogCreate) SetOutputTokens(v int) *CodexResponseLogCreate {
	_c.mutation.SetOutputTokens(v)
	return _c
}

// SetCacheRate sets the "cache_rate" field.
func (_c *CodexResponseLogCreate) SetCacheRate(v float64) *CodexResponseLogCreate {
	_c.mutation.SetCacheRate(v)
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *CodexResponseLogCreate) SetDurationMs(v int) *CodexResponseLogCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *CodexResponseLogCreate) SetAccountID(v string) *CodexResponseLogCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetAccountName sets the "account_name" field.
func (_c *CodexResponseLogCreate) SetAccountName(v string) *CodexResponseLogCreate {
	_c.mutation.SetAccountName(v)
	return _c
}

// SetIsSse sets the "is_sse" field.
func (_c *CodexResponseLogCreate) SetIsSse(v bool) *CodexResponseLogCreate {
	_c.mutation.SetIsSse(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CodexResponseLogCreate) SetCreatedAt(v time.Time) *CodexResponseLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CodexResponseLogCreate) SetNillableCreatedAt(v *time.Time) *CodexResponseLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the CodexResponseLogMutation object of the builder.
func (_c *CodexResponseLogCreate) Mutation() *CodexResponseLogMutation {
	return _c.mutation
}

// Save creates the CodexResponseLog in the database.
func (_c *CodexResponseLogCreate) Save(ctx context.Context) (*CodexResponseLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CodexResponseLogCreate) SaveX(ctx context.Context) *CodexResponseLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexResponseLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexResponseLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CodexResponseLogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := codexresponselog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CodexResponseLogCreate) check() error {
	if _, ok := _c.mutation.UserAgent(); !ok {
		return &ValidationError{Name: "user_agent", err: errors.New(`ent: missing required field "CodexResponseLog.user_agent"`)}
	}
	if _, ok := _c.mutation.ClientIP(); !ok {
		return &ValidationError{Name: "client_ip", err: errors.New(`ent: missing required field "CodexResponseLog.client_ip"`)}
	}
	if _, ok := _c.mutation.InputTokens(); !ok {
		return &ValidationError{Name: "input_tokens", err: errors.New(`ent: missing required field "CodexResponseLog.input_tokens"`)}
	}
	if _, ok := _c.mutation.CachedInputTokens(); !ok {
		return &ValidationError{Name: "cached_input_tokens", err: errors.New(`ent: missing required field "CodexResponseLog.cached_input_tokens"`)}
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		return &ValidationError{Name: "output_tokens", err: errors.New(`ent: missing required field "CodexResponseLog.output_tokens"`)}
	}
	if _, ok := _c.mutation.CacheRate(); !ok {
		return &ValidationError{Name: "cache_rate", err: errors.New(`ent: missing required field "CodexResponseLog.cache_rate"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "CodexResponseLog.duration_ms"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "CodexResponseLog.account_id"`)}
	}
	if _, ok := _c.mutation.AccountName(); !ok {
		return &ValidationError{Name: "account_name", err: errors.New(`ent: missing required field "CodexResponseLog.account_name"`)}
	}
	if _, ok := _c.mutation.IsSse(); !ok {
		return &ValidationError{Name: "is_sse", err: errors.New(`ent: missing required field "CodexResponseLog.is_sse"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CodexResponseLog.created_at"`)}
	}
	return nil
}

func (_c *CodexResponseLogCreate) sqlSave(ctx context.Context) (*CodexResponseLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CodexResponseLogCreate) createSpec() (*CodexResponseLog, *sqlgraph.CreateSpec) {
	var (
		_node = &CodexResponseLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(codexresponselog.Table, sqlgraph.NewFieldSpec(codexresponselog.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(codexresponselog.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.ClientIP(); ok {
		_spec.SetField(codexresponselog.FieldClientIP, field.TypeString, value)
		_node.ClientIP = value
	}
	if value, ok := _c.mutation.InputTokens(); ok {
		_spec.SetField(codexresponselog.FieldInputTokens, field.TypeInt, value)
		_node.InputTokens = value
	}
	if value, ok := _c.mutation.CachedInputTokens(); ok {
		_spec.SetField(codexresponselog.FieldCachedInputTokens, field.TypeInt, value)
		_node.CachedInputTokens = value
	}
	if value, ok := _c.mutation.OutputTokens(); ok {
		_spec.SetField(codexresponselog.FieldOutputTokens, field.TypeInt, value)
		_node.OutputTokens = value
	}
	if value, ok := _c.mutation.CacheRate(); ok {
		_spec.SetField(codexresponselog.FieldCacheRate, field.TypeFloat64, value)
		_node.CacheRate = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(codexresponselog.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(codexresponselog.FieldAccountID, field.TypeString, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.AccountName(); ok {
		_spec.SetField(codexresponselog.FieldAccountName, field.TypeString, value)
		_node.AccountName = value
	}
	if value, ok := _c.mutation.IsSse(); ok {
		_spec.SetField(codexresponselog.FieldIsSse, field.TypeBool, value)
		_node.IsSse = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(codexresponselog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// CodexResponseLogCreateBulk is the builder for creating many CodexResponseLog entities in bulk.
type CodexResponseLogCreateBulk struct {
	config
	err      error
	builders []*CodexResponseLogCreate
}

// Save creates the CodexResponseLog entities in the database.
func (_c *CodexResponseLogCreateBulk) Save(ctx context.Context) ([]*CodexResponseLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CodexResponseLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CodexResponseLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CodexResponseLogCreateBulk) SaveX(ctx context.Context) []*CodexResponseLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexResponseLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexResponseLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
