// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"myapi/internal/ent/codexoauthsession"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CodexOAuthSession is the model entity for the CodexOAuthSession schema.
type CodexOAuthSession struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// CodeVerifier holds the value of the "code_verifier" field.
	CodeVerifier string `json:"code_verifier,omitempty"`
	// CodeChallenge holds the value of the "code_challenge" field.
	CodeChallenge string `json:"code_challenge,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CodexOAuthSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case codexoauthsession.FieldID:
			values[i] = new(sql.NullInt64)
		case codexoauthsession.FieldState, codexoauthsession.FieldCodeVerifier, codexoauthsession.FieldCodeChallenge:
			values[i] = new(sql.NullString)
		case codexoauthsession.FieldExpiresAt, codexoauthsession.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CodexOAuthSession fields.
func (_m *CodexOAuthSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case codexoauthsession.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case codexoauthsession.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case codexoauthsession.FieldCodeVerifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code_verifier", values[i])
			} else if value.Valid {
				_m.CodeVerifier = value.String
			}
		case codexoauthsession.FieldCodeChallenge:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code_challenge", values[i])
			} else if value.Valid {
				_m.CodeChallenge = value.String
			}
		case codexoauthsession.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case codexoauthsession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CodexOAuthSession.
// This includes values selected through modifiers, order, etc.
func (_m *CodexOAuthSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CodexOAuthSession.
// Note that you need to call CodexOAuthSession.Unwrap() before calling this method if this CodexOAuthSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CodexOAuthSession) Update() *CodexOAuthSessionUpdateOne {
	return NewCodexOAuthSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CodexOAuthSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CodexOAuthSession) Unwrap() *CodexOAuthSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CodexOAuthSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CodexOAuthSession) String() string {
	var builder strings.Builder
	builder.WriteString("CodexOAuthSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	builder.WriteString("code_verifier=")
	builder.WriteString(_m.CodeVerifier)
	builder.WriteString(", ")
	builder.WriteString("code_challenge=")
	builder.WriteString(_m.CodeChallenge)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CodexOAuthSessions is a parsable slice of CodexOAuthSession.
type CodexOAuthSessions []*CodexOAuthSession
