// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"myapi/internal/ent/codexresponselog"
	"myapi/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CodexResponseLogUpdate is the builder for updating CodexResponseLog entities.
type CodexResponseLogUpdate struct {
	config
	hooks    []Hook
	mutation *CodexResponseLogMutation
}

// Where appends a list predicates to the CodexResponseLogUpdate builder.
func (_u *CodexResponseLogUpdate) Where(ps ...predicate.CodexResponseLog) *CodexResponseLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *CodexResponseLogUpdate) SetUserAgent(v string) *CodexResponseLogUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *CodexResponseLogUpdate) SetNillableUserAgent(v *string) *CodexResponseLogUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *CodexResponseLogUpdate) SetClientIP(v string) *CodexResponseLogUpdate {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *CodexResponseLogUpdate) SetNillableClientIP(v *string) *CodexResponseLogUpdate {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *CodexResponseLogUpdate) SetInputTokens(v int) *CodexResponseLogUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *CodexResponseLogUpdate) SetNillableInputTokens(v *int) *CodexResponseLogUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *CodexResponseLogUpdate) AddInputTokens(v int) *CodexResponseLogUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetCachedInputTokens sets the "cached_input_tokens" field.
func (_u *CodexResponseLogUpdate) SetCachedInputTokens(v int) *CodexResponseLogUpdate {
	_u.mutation.ResetCachedInputTokens()
	_u.mutation.SetCachedInputTokens(v)
	return _u
}

// SetNillableCachedInputTokens sets the "cached_input_tokens" field if the given value is not nil.
func (_u *CodexResponseLogUpdate) SetNillableCachedInputTokens(v *int) *CodexResponseLogUpdate {
	if v != nil {
		_u.SetCachedInputTokens(*v)
	}
	return _u
}

// AddCachedInputTokens adds value to the "cached_input_tokens" field.
func (_u *CodexResponseLogUpdate) AddCachedInputTokens(v int) *CodexResponseLogUpdate {
	_u.mutation.AddCachedInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *CodexResponseLogUpdate) SetOutputTokens(v int) *CodexResponseLogUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *CodexResponseLogUpdate) SetNillableOutputTokens(v *int) *CodexResponseLogUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *CodexResponseLogUpdate) AddOutputTokens(v int) *CodexResponseLogUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCacheRate sets the "cache_rate" field.
func (_u *CodexResponseLogUpdate) SetCacheRate(v float64) *CodexResponseLogUpdate {
	_u.mutation.ResetCacheRate()
	_u.mutation.SetCacheRate(v)
	return _u
}

// SetNillableCacheRate sets the "cache_rate" field if the given value is not nil.
func (_u *CodexResponseLogUpdate) SetNillableCacheRate(v *float64) *CodexResponseLogUpdate {
	if v != nil {
		_u.SetCacheRate(*v)
	}
	return _u
}

// AddCacheRate adds value to the "cache_rate" field.
func (_u *CodexResponseLogUpdate) AddCacheRate(v float64) *CodexResponseLogUpdate {
	_u.mutation.AddCacheRate(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *CodexResponseLogUpdate) SetDurationMs(v int) *CodexResponseLogUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *CodexResponseLogUpdate) SetNillableDurationMs(v *int) *CodexResponseLogUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *CodexResponseLogUpdate) AddDurationMs(v int) *CodexResponseLogUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *CodexResponseLogUpdate) SetAccountID(v string) *CodexResponseLogUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *CodexResponseLogUpdate) SetNillableAccountID(v *string) *CodexResponseLogUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetAccountName sets the "account_name" field.
func (_u *CodexResponseLogUpdate) SetAccountName(v string) *CodexResponseLogUpdate {
	_u.mutation.SetAccountName(v)
	return _u
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (_u *CodexResponseLogUpdate) SetNillableAccountName(v *string) *CodexResponseLogUpdate {
	if v != nil {
		_u.SetAccountName(*v)
	}
	return _u
}

// SetIsSse sets the "is_sse" field.
func (_u *CodexResponseLogUpdate) SetIsSse(v bool) *CodexResponseLogUpdate {
	_u.mutation.SetIsSse(v)
	return _u
}

// SetNillableIsSse sets the "is_sse" field if the given value is not nil.
func (_u *CodexResponseLogUpdate) SetNillableIsSse(v *bool) *CodexResponseLogUpdate {
	if v != nil {
		_u.SetIsSse(*v)
	}
	return _u
}

// Mutation returns the CodexResponseLogMutation object of the builder.
func (_u *CodexResponseLogUpdate) Mutation() *CodexResponseLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CodexResponseLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexResponseLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CodexResponseLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexResponseLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CodexResponseLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(codexresponselog.Table, codexresponselog.Columns, sqlgraph.NewFieldSpec(codexresponselog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(codexresponselog.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(codexresponselog.FieldClientIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(codexresponselog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(codexresponselog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CachedInputTokens(); ok {
		_spec.SetField(codexresponselog.FieldCachedInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCachedInputTokens(); ok {
		_spec.AddField(codexresponselog.FieldCachedInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(codexresponselog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(codexresponselog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CacheRate(); ok {
		_spec.SetField(codexresponselog.FieldCacheRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheRate(); ok {
		_spec.AddField(codexresponselog.FieldCacheRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(codexresponselog.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(codexresponselog.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(codexresponselog.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountName(); ok {
		_spec.SetField(codexresponselog.FieldAccountName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsSse(); ok {
		_spec.SetField(codexresponselog.FieldIsSse, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexresponselog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CodexResponseLogUpdateOne is the builder for updating a single CodexResponseLog entity.
type CodexResponseLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CodexResponseLogMutation
}

// SetUserAgent sets the "user_agent" field.
func (_u *CodexResponseLogUpdateOne) SetUserAgent(v string) *CodexResponseLogUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *CodexResponseLogUpdateOne) SetNillableUserAgent(v *string) *CodexResponseLogUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *CodexResponseLogUpdateOne) SetClientIP(v string) *CodexResponseLogUpdateOne {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *CodexResponseLogUpdateOne) SetNillableClientIP(v *string) *CodexResponseLogUpdateOne {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *CodexResponseLogUpdateOne) SetInputTokens(v int) *CodexResponseLogUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *CodexResponseLogUpdateOne) SetNillableInputTokens(v *int) *CodexResponseLogUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *CodexResponseLogUpdateOne) AddInputTokens(v int) *CodexResponseLogUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetCachedInputTokens sets the "cached_input_tokens" field.
func (_u *CodexResponseLogUpdateOne) SetCachedInputTokens(v int) *CodexResponseLogUpdateOne {
	_u.mutation.ResetCachedInputTokens()
	_u.mutation.SetCachedInputTokens(v)
	return _u
}

// SetNillableCachedInputTokens sets the "cached_input_tokens" field if the given value is not nil.
func (_u *CodexResponseLogUpdateOne) SetNillableCachedInputTokens(v *int) *CodexResponseLogUpdateOne {
	if v != nil {
		_u.SetCachedInputTokens(*v)
	}
	return _u
}

// AddCachedInputTokens adds value to the "cached_input_tokens" field.
func (_u *CodexResponseLogUpdateOne) AddCachedInputTokens(v int) *CodexResponseLogUpdateOne {
	_u.mutation.AddCachedInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *CodexResponseLogUpdateOne) SetOutputTokens(v int) *CodexResponseLogUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *CodexResponseLogUpdateOne) SetNillableOutputTokens(v *int) *CodexResponseLogUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *CodexResponseLogUpdateOne) AddOutputTokens(v int) *CodexResponseLogUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCacheRate sets the "cache_rate" field.
func (_u *CodexResponseLogUpdateOne) SetCacheRate(v float64) *CodexResponseLogUpdateOne {
	_u.mutation.ResetCacheRate()
	_u.mutation.SetCacheRate(v)
	return _u
}

// SetNillableCacheRate sets the "cache_rate" field if the given value is not nil.
func (_u *CodexResponseLogUpdateOne) SetNillableCacheRate(v *float64) *CodexResponseLogUpdateOne {
	if v != nil {
		_u.SetCacheRate(*v)
	}
	return _u
}

// AddCacheRate adds value to the "cache_rate" field.
func (_u *CodexResponseLogUpdateOne) AddCacheRate(v float64) *CodexResponseLogUpdateOne {
	_u.mutation.AddCacheRate(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *CodexResponseLogUpdateOne) SetDurationMs(v int) *CodexResponseLogUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *CodexResponseLogUpdateOne) SetNillableDurationMs(v *int) *CodexResponseLogUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *CodexResponseLogUpdateOne) AddDurationMs(v int) *CodexResponseLogUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *CodexResponseLogUpdateOne) SetAccountID(v string) *CodexResponseLogUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *CodexResponseLogUpdateOne) SetNillableAccountID(v *string) *CodexResponseLogUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetAccountName sets the "account_name" field.
func (_u *CodexResponseLogUpdateOne) SetAccountName(v string) *CodexResponseLogUpdateOne {
	_u.mutation.SetAccountName(v)
	return _u
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (_u *CodexResponseLogUpdateOne) SetNillableAccountName(v *string) *CodexResponseLogUpdateOne {
	if v != nil {
		_u.SetAccountName(*v)
	}
	return _u
}

// SetIsSse sets the "is_sse" field.
func (_u *CodexResponseLogUpdateOne) SetIsSse(v bool) *CodexResponseLogUpdateOne {
	_u.mutation.SetIsSse(v)
	return _u
}

// SetNillableIsSse sets the "is_sse" field if the given value is not nil.
func (_u *CodexResponseLogUpdateOne) SetNillableIsSse(v *bool) *CodexResponseLogUpdateOne {
	if v != nil {
		_u.SetIsSse(*v)
	}
	return _u
}

// Mutation returns the CodexResponseLogMutation object of the builder.
func (_u *CodexResponseLogUpdateOne) Mutation() *CodexResponseLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the CodexResponseLogUpdate builder.
func (_u *CodexResponseLogUpdateOne) Where(ps ...predicate.CodexResponseLog) *CodexResponseLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CodexResponseLogUpdateOne) Select(field string, fields ...string) *CodexResponseLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CodexResponseLog entity.
func (_u *CodexResponseLogUpdateOne) Save(ctx context.Context) (*CodexResponseLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexResponseLogUpdateOne) SaveX(ctx context.Context) *CodexResponseLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CodexResponseLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexResponseLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CodexResponseLogUpdateOne) sqlSave(ctx context.Context) (_node *CodexResponseLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(codexresponselog.Table, codexresponselog.Columns, sqlgraph.NewFieldSpec(codexresponselog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CodexResponseLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, codexresponselog.FieldID)
		for _, f := range fields {
			if !codexresponselog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != codexresponselog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(codexresponselog.FieldUserAgent, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(codexresponselog.FieldClientIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(codexresponselog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(codexresponselog.FieldInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CachedInputTokens(); ok {
		_spec.SetField(codexresponselog.FieldCachedInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCachedInputTokens(); ok {
		_spec.AddField(codexresponselog.FieldCachedInputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(codexresponselog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(codexresponselog.FieldOutputTokens, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CacheRate(); ok {
		_spec.SetField(codexresponselog.FieldCacheRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCacheRate(); ok {
		_spec.AddField(codexresponselog.FieldCacheRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(codexresponselog.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(codexresponselog.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(codexresponselog.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountName(); ok {
		_spec.SetField(codexresponselog.FieldAccountName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsSse(); ok {
		_spec.SetField(codexresponselog.FieldIsSse, field.TypeBool, value)
	}
	_node = &CodexResponseLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexresponselog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
