// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"myapi/internal/ent/codexoauthsession"
	"myapi/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CodexOAuthSessionUpdate is the builder for updating CodexOAuthSession entities.
type CodexOAuthSessionUpdate struct {
	config
	hooks    []Hook
	mutation *CodexOAuthSessionMutation
}

// Where appends a list predicates to the CodexOAuthSessionUpdate builder.
func (_u *CodexOAuthSessionUpdate) Where(ps ...predicate.CodexOAuthSession) *CodexOAuthSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetState sets the "state" field.
func (_u *CodexOAuthSessionUpdate) SetState(v string) *CodexOAuthSessionUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *CodexOAuthSessionUpdate) SetNillableState(v *string) *CodexOAuthSessionUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetCodeVerifier sets the "code_verifier" field.
func (_u *CodexOAuthSessionUpdate) SetCodeVerifier(v string) *CodexOAuthSessionUpdate {
	_u.mutation.SetCodeVerifier(v)
	return _u
}

// SetNillableCodeVerifier sets the "code_verifier" field if the given value is not nil.
func (_u *CodexOAuthSessionUpdate) SetNillableCodeVerifier(v *string) *CodexOAuthSessionUpdate {
	if v != nil {
		_u.SetCodeVerifier(*v)
	}
	return _u
}

// SetCodeChallenge sets the "code_challenge" field.
func (_u *CodexOAuthSessionUpdate) SetCodeChallenge(v string) *CodexOAuthSessionUpdate {
	_u.mutation.SetCodeChallenge(v)
	return _u
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_u *CodexOAuthSessionUpdate) SetNillableCodeChallenge(v *string) *CodexOAuthSessionUpdate {
	if v != nil {
		_u.SetCodeChallenge(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CodexOAuthSessionUpdate) SetExpiresAt(v time.Time) *CodexOAuthSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CodexOAuthSessionUpdate) SetNillableExpiresAt(v *time.Time) *CodexOAuthSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the CodexOAuthSessionMutation object of the builder.
func (_u *CodexOAuthSessionUpdate) Mutation() *CodexOAuthSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CodexOAuthSessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexOAuthSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CodexOAuthSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexOAuthSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CodexOAuthSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(codexoauthsession.Table, codexoauthsession.Columns, sqlgraph.NewFieldSpec(codexoauthsession.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(codexoauthsession.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeVerifier(); ok {
		_spec.SetField(codexoauthsession.FieldCodeVerifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallenge(); ok {
		_spec.SetField(codexoauthsession.FieldCodeChallenge, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(codexoauthsession.FieldExpiresAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexoauthsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CodexOAuthSessionUpdateOne is the builder for updating a single CodexOAuthSession entity.
type CodexOAuthSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CodexOAuthSessionMutation
}

// SetState sets the "state" field.
func (_u *CodexOAuthSessionUpdateOne) SetState(v string) *CodexOAuthSessionUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *CodexOAuthSessionUpdateOne) SetNillableState(v *string) *CodexOAuthSessionUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetCodeVerifier sets the "code_verifier" field.
func (_u *CodexOAuthSessionUpdateOne) SetCodeVerifier(v string) *CodexOAuthSessionUpdateOne {
	_u.mutation.SetCodeVerifier(v)
	return _u
}

// SetNillableCodeVerifier sets the "code_verifier" field if the given value is not nil.
func (_u *CodexOAuthSessionUpdateOne) SetNillableCodeVerifier(v *string) *CodexOAuthSessionUpdateOne {
	if v != nil {
		_u.SetCodeVerifier(*v)
	}
	return _u
}

// SetCodeChallenge sets the "code_challenge" field.
func (_u *CodexOAuthSessionUpdateOne) SetCodeChallenge(v string) *CodexOAuthSessionUpdateOne {
	_u.mutation.SetCodeChallenge(v)
	return _u
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_u *CodexOAuthSessionUpdateOne) SetNillableCodeChallenge(v *string) *CodexOAuthSessionUpdateOne {
	if v != nil {
		_u.SetCodeChallenge(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CodexOAuthSessionUpdateOne) SetExpiresAt(v time.Time) *CodexOAuthSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CodexOAuthSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *CodexOAuthSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the CodexOAuthSessionMutation object of the builder.
func (_u *CodexOAuthSessionUpdateOne) Mutation() *CodexOAuthSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the CodexOAuthSessionUpdate builder.
func (_u *CodexOAuthSessionUpdateOne) Where(ps ...predicate.CodexOAuthSession) *CodexOAuthSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CodexOAuthSessionUpdateOne) Select(field string, fields ...string) *CodexOAuthSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CodexOAuthSession entity.
func (_u *CodexOAuthSessionUpdateOne) Save(ctx context.Context) (*CodexOAuthSession, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexOAuthSessionUpdateOne) SaveX(ctx context.Context) *CodexOAuthSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CodexOAuthSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexOAuthSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CodexOAuthSessionUpdateOne) sqlSave(ctx context.Context) (_node *CodexOAuthSession, err error) {
	_spec := sqlgraph.NewUpdateSpec(codexoauthsession.Table, codexoauthsession.Columns, sqlgraph.NewFieldSpec(codexoauthsession.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CodexOAuthSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, codexoauthsession.FieldID)
		for _, f := range fields {
			if !codexoauthsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != codexoauthsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(codexoauthsession.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeVerifier(); ok {
		_spec.SetField(codexoauthsession.FieldCodeVerifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.CodeChallenge(); ok {
		_spec.SetField(codexoauthsession.FieldCodeChallenge, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(codexoauthsession.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &CodexOAuthSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexoauthsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
