// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"myapi/internal/ent/codexresponselog"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CodexResponseLog is the model entity for the CodexResponseLog schema.
type CodexResponseLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserAgent holds the value of the "user_agent" field.
	UserAgent string `json:"user_agent,omitempty"`
	// ClientIP holds the value of the "client_ip" field.
	ClientIP string `json:"client_ip,omitempty"`
	// InputTokens holds the value of the "input_tokens" field.
	InputTokens int `json:"input_tokens,omitempty"`
	// CachedInputTokens holds the value of the "cached_input_tokens" field.
	CachedInputTokens int `json:"cached_input_tokens,omitempty"`
	// OutputTokens holds the value of the "output_tokens" field.
	OutputTokens int `json:"output_tokens,omitempty"`
	// CacheRate holds the value of the "cache_rate" field.
	CacheRate float64 `json:"cache_rate,omitempty"`
	// DurationMs holds the value of the "duration_ms" field.
	DurationMs int `json:"duration_ms,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID string `json:"account_id,omitempty"`
	// AccountName holds the value of the "account_name" field.
	AccountName string `json:"account_name,omitempty"`
	// IsSse holds the value of the "is_sse" field.
	IsSse bool `json:"is_sse,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CodexResponseLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case codexresponselog.FieldIsSse:
			values[i] = new(sql.NullBool)
		case codexresponselog.FieldCacheRate:
			values[i] = new(sql.NullFloat64)
		case codexresponselog.FieldID, codexresponselog.FieldInputTokens, codexresponselog.FieldCachedInputTokens, codexresponselog.FieldOutputTokens, codexresponselog.FieldDurationMs:
			values[i] = new(sql.NullInt64)
		case codexresponselog.FieldUserAgent, codexresponselog.FieldClientIP, codexresponselog.FieldAccountID, codexresponselog.FieldAccountName:
			values[i] = new(sql.NullString)
		case codexresponselog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CodexResponseLog fields.
func (_m *CodexResponseLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case codexresponselog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case codexresponselog.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case codexresponselog.FieldClientIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_ip", values[i])
			} else if value.Valid {
				_m.ClientIP = value.String
			}
		case codexresponselog.FieldInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field input_tokens", values[i])
			} else if value.Valid {
				_m.InputTokens = int(value.Int64)
			}
		case codexresponselog.FieldCachedInputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cached_input_tokens", values[i])
			} else if value.Valid {
				_m.CachedInputTokens = int(value.Int64)
			}
		case codexresponselog.FieldOutputTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field output_tokens", values[i])
			} else if value.Valid {
				_m.OutputTokens = int(value.Int64)
			}
		case codexresponselog.FieldCacheRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cache_rate", values[i])
			} else if value.Valid {
				_m.CacheRate = value.Float64
			}
		case codexresponselog.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = int(value.Int64)
			}
		case codexresponselog.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.String
			}
		case codexresponselog.FieldAccountName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_name", values[i])
			} else if value.Valid {
				_m.AccountName = value.String
			}
		case codexresponselog.FieldIsSse:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_sse", values[i])
			} else if value.Valid {
				_m.IsSse = value.Bool
			}
		case codexresponselog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CodexResponseLog.
// This includes values selected through modifiers, order, etc.
func (_m *CodexResponseLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CodexResponseLog.
// Note that you need to call CodexResponseLog.Unwrap() before calling this method if this CodexResponseLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CodexResponseLog) Update() *CodexResponseLogUpdateOne {
	return NewCodexResponseLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CodexResponseLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CodexResponseLog) Unwrap() *CodexResponseLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CodexResponseLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CodexResponseLog) String() string {
	var builder strings.Builder
	builder.WriteString("CodexResponseLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_agent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("client_ip=")
	builder.WriteString(_m.ClientIP)
	builder.WriteString(", ")
	builder.WriteString("input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.InputTokens))
	builder.WriteString(", ")
	builder.WriteString("cached_input_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CachedInputTokens))
	builder.WriteString(", ")
	builder.WriteString("output_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutputTokens))
	builder.WriteString(", ")
	builder.WriteString("cache_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheRate))
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationMs))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(_m.AccountID)
	builder.WriteString(", ")
	builder.WriteString("account_name=")
	builder.WriteString(_m.AccountName)
	builder.WriteString(", ")
	builder.WriteString("is_sse=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsSse))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CodexResponseLogs is a parsable slice of CodexResponseLog.
type CodexResponseLogs []*CodexResponseLog
