// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"myapi/internal/ent/codexoauthsession"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CodexOAuthSessionCreate is the builder for creating a CodexOAuthSession entity.
type CodexOAuthSessionCreate struct {
	config
	mutation *CodexOAuthSessionMutation
	hooks    []Hook
}

// SetState sets the "state" field.
func (_c *CodexOAuthSessionCreate) SetState(v string) *CodexOAuthSessionCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetCodeVerifier sets the "code_verifier" field.
func (_c *CodexOAuthSessionCreate) SetCodeVerifier(v string) *CodexOAuthSessionCreate {
	_c.mutation.SetCodeVerifier(v)
	return _c
}

// SetCodeChallenge sets the "code_challenge" field.
func (_c *CodexOAuthSessionCreate) SetCodeChallenge(v string) *CodexOAuthSessionCreate {
	_c.mutation.SetCodeChallenge(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *CodexOAuthSessionCreate) SetExpiresAt(v time.Time) *CodexOAuthSessionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CodexOAuthSessionCreate) SetCreatedAt(v time.Time) *CodexOAuthSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CodexOAuthSessionCreate) SetNillableCreatedAt(v *time.Time) *CodexOAuthSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the CodexOAuthSessionMutation object of the builder.
func (_c *CodexOAuthSessionCreate) Mutation() *CodexOAuthSessionMutation {
	return _c.mutation
}

// Save creates the CodexOAuthSession in the database.
func (_c *CodexOAuthSessionCreate) Save(ctx context.Context) (*CodexOAuthSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CodexOAuthSessionCreate) SaveX(ctx context.Context) *CodexOAuthSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexOAuthSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexOAuthSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CodexOAuthSessionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := codexoauthsession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CodexOAuthSessionCreate) check() error {
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "CodexOAuthSession.state"`)}
	}
	if _, ok := _c.mutation.CodeVerifier(); !ok {
		return &ValidationError{Name: "code_verifier", err: errors.New(`ent: missing required field "CodexOAuthSession.code_verifier"`)}
	}
	if _, ok := _c.mutation.CodeChallenge(); !ok {
		return &ValidationError{Name: "code_challenge", err: errors.New(`ent: missing required field "CodexOAuthSession.code_challenge"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "CodexOAuthSession.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CodexOAuthSession.created_at"`)}
	}
	return nil
}

func (_c *CodexOAuthSessionCreate) sqlSave(ctx context.Context) (*CodexOAuthSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CodexOAuthSessionCreate) createSpec() (*CodexOAuthSession, *sqlgraph.CreateSpec) {
	var (
		_node = &CodexOAuthSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(codexoauthsession.Table, sqlgraph.NewFieldSpec(codexoauthsession.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(codexoauthsession.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.CodeVerifier(); ok {
		_spec.SetField(codexoauthsession.FieldCodeVerifier, field.TypeString, value)
		_node.CodeVerifier = value
	}
	if value, ok := _c.mutation.CodeChallenge(); ok {
		_spec.SetField(codexoauthsession.FieldCodeChallenge, field.TypeString, value)
		_node.CodeChallenge = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(codexoauthsession.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(codexoauthsession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// CodexOAuthSessionCreateBulk is the builder for creating many CodexOAuthSession entities in bulk.
type CodexOAuthSessionCreateBulk struct {
	config
	err      error
	builders []*CodexOAuthSessionCreate
}

// Save creates the CodexOAuthSession entities in the database.
func (_c *CodexOAuthSessionCreateBulk) Save(ctx context.Context) ([]*CodexOAuthSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CodexOAuthSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CodexOAuthSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CodexOAuthSessionCreateBulk) SaveX(ctx context.Context) []*CodexOAuthSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexOAuthSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexOAuthSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
