// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"myapi/internal/ent/codexaccount"
	"myapi/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// CodexAccountUpdate is the builder for updating CodexAccount entities.
type CodexAccountUpdate struct {
	config
	hooks    []Hook
	mutation *CodexAccountMutation
}

// Where appends a list predicates to the CodexAccountUpdate builder.
func (_u *CodexAccountUpdate) Where(ps ...predicate.CodexAccount) *CodexAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CodexAccountUpdate) SetName(v string) *CodexAccountUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CodexAccountUpdate) SetNillableName(v *string) *CodexAccountUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *CodexAccountUpdate) SetAccountID(v string) *CodexAccountUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *CodexAccountUpdate) SetNillableAccountID(v *string) *CodexAccountUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *CodexAccountUpdate) SetToken(v string) *CodexAccountUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *CodexAccountUpdate) SetNillableToken(v *string) *CodexAccountUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CodexAccountUpdate) SetExpiresAt(v time.Time) *CodexAccountUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CodexAccountUpdate) SetNillableExpiresAt(v *time.Time) *CodexAccountUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetOauthPayload sets the "oauth_payload" field.
func (_u *CodexAccountUpdate) SetOauthPayload(v json.RawMessage) *CodexAccountUpdate {
	_u.mutation.SetOauthPayload(v)
	return _u
}

// AppendOauthPayload appends value to the "oauth_payload" field.
func (_u *CodexAccountUpdate) AppendOauthPayload(v json.RawMessage) *CodexAccountUpdate {
	_u.mutation.AppendOauthPayload(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CodexAccountUpdate) SetUpdatedAt(v time.Time) *CodexAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CodexAccountMutation object of the builder.
func (_u *CodexAccountUpdate) Mutation() *CodexAccountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CodexAccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CodexAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CodexAccountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := codexaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CodexAccountUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := codexaccount.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CodexAccount.name": %w`, err)}
		}
	}
	return nil
}

func (_u *CodexAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(codexaccount.Table, codexaccount.Columns, sqlgraph.NewFieldSpec(codexaccount.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(codexaccount.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(codexaccount.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(codexaccount.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(codexaccount.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OauthPayload(); ok {
		_spec.SetField(codexaccount.FieldOauthPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOauthPayload(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, codexaccount.FieldOauthPayload, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(codexaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CodexAccountUpdateOne is the builder for updating a single CodexAccount entity.
type CodexAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CodexAccountMutation
}

// SetName sets the "name" field.
func (_u *CodexAccountUpdateOne) SetName(v string) *CodexAccountUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CodexAccountUpdateOne) SetNillableName(v *string) *CodexAccountUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *CodexAccountUpdateOne) SetAccountID(v string) *CodexAccountUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *CodexAccountUpdateOne) SetNillableAccountID(v *string) *CodexAccountUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *CodexAccountUpdateOne) SetToken(v string) *CodexAccountUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *CodexAccountUpdateOne) SetNillableToken(v *string) *CodexAccountUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CodexAccountUpdateOne) SetExpiresAt(v time.Time) *CodexAccountUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CodexAccountUpdateOne) SetNillableExpiresAt(v *time.Time) *CodexAccountUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetOauthPayload sets the "oauth_payload" field.
func (_u *CodexAccountUpdateOne) SetOauthPayload(v json.RawMessage) *CodexAccountUpdateOne {
	_u.mutation.SetOauthPayload(v)
	return _u
}

// AppendOauthPayload appends value to the "oauth_payload" field.
func (_u *CodexAccountUpdateOne) AppendOauthPayload(v json.RawMessage) *CodexAccountUpdateOne {
	_u.mutation.AppendOauthPayload(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CodexAccountUpdateOne) SetUpdatedAt(v time.Time) *CodexAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CodexAccountMutation object of the builder.
func (_u *CodexAccountUpdateOne) Mutation() *CodexAccountMutation {
	return _u.mutation
}

// Where appends a list predicates to the CodexAccountUpdate builder.
func (_u *CodexAccountUpdateOne) Where(ps ...predicate.CodexAccount) *CodexAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CodexAccountUpdateOne) Select(field string, fields ...string) *CodexAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CodexAccount entity.
func (_u *CodexAccountUpdateOne) Save(ctx context.Context) (*CodexAccount, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CodexAccountUpdateOne) SaveX(ctx context.Context) *CodexAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CodexAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CodexAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CodexAccountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := codexaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CodexAccountUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := codexaccount.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CodexAccount.name": %w`, err)}
		}
	}
	return nil
}

func (_u *CodexAccountUpdateOne) sqlSave(ctx context.Context) (_node *CodexAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(codexaccount.Table, codexaccount.Columns, sqlgraph.NewFieldSpec(codexaccount.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CodexAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, codexaccount.FieldID)
		for _, f := range fields {
			if !codexaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != codexaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(codexaccount.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(codexaccount.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(codexaccount.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(codexaccount.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OauthPayload(); ok {
		_spec.SetField(codexaccount.FieldOauthPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOauthPayload(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, codexaccount.FieldOauthPayload, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(codexaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &CodexAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{codexaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
