// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"myapi/internal/ent/codexaccount"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CodexAccountCreate is the builder for creating a CodexAccount entity.
type CodexAccountCreate struct {
	config
	mutation *CodexAccountMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *CodexAccountCreate) SetName(v string) *CodexAccountCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *CodexAccountCreate) SetAccountID(v string) *CodexAccountCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetToken sets the "token" field.
func (_c *CodexAccountCreate) SetToken(v string) *CodexAccountCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *CodexAccountCreate) SetExpiresAt(v time.Time) *CodexAccountCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetOauthPayload sets the "oauth_payload" field.
func (_c *CodexAccountCreate) SetOauthPayload(v json.RawMessage) *CodexAccountCreate {
	_c.mutation.SetOauthPayload(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CodexAccountCreate) SetCreatedAt(v time.Time) *CodexAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CodexAccountCreate) SetNillableCreatedAt(v *time.Time) *CodexAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CodexAccountCreate) SetUpdatedAt(v time.Time) *CodexAccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CodexAccountCreate) SetNillableUpdatedAt(v *time.Time) *CodexAccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the CodexAccountMutation object of the builder.
func (_c *CodexAccountCreate) Mutation() *CodexAccountMutation {
	return _c.mutation
}

// Save creates the CodexAccount in the database.
func (_c *CodexAccountCreate) Save(ctx context.Context) (*CodexAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CodexAccountCreate) SaveX(ctx context.Context) *CodexAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CodexAccountCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := codexaccount.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := codexaccount.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CodexAccountCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CodexAccount.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := codexaccount.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "CodexAccount.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "CodexAccount.account_id"`)}
	}
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "CodexAccount.token"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "CodexAccount.expires_at"`)}
	}
	if _, ok := _c.mutation.OauthPayload(); !ok {
		return &ValidationError{Name: "oauth_payload", err: errors.New(`ent: missing required field "CodexAccount.oauth_payload"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CodexAccount.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CodexAccount.updated_at"`)}
	}
	return nil
}

func (_c *CodexAccountCreate) sqlSave(ctx context.Context) (*CodexAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CodexAccountCreate) createSpec() (*CodexAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &CodexAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(codexaccount.Table, sqlgraph.NewFieldSpec(codexaccount.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(codexaccount.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(codexaccount.FieldAccountID, field.TypeString, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(codexaccount.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(codexaccount.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.OauthPayload(); ok {
		_spec.SetField(codexaccount.FieldOauthPayload, field.TypeJSON, value)
		_node.OauthPayload = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(codexaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(codexaccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// CodexAccountCreateBulk is the builder for creating many CodexAccount entities in bulk.
type CodexAccountCreateBulk struct {
	config
	err      error
	builders []*CodexAccountCreate
}

// Save creates the CodexAccount entities in the database.
func (_c *CodexAccountCreateBulk) Save(ctx context.Context) ([]*CodexAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CodexAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CodexAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CodexAccountCreateBulk) SaveX(ctx context.Context) []*CodexAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CodexAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CodexAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
