// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"myapi/internal/ent/codexresponselog"
	"myapi/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CodexResponseLogDelete is the builder for deleting a CodexResponseLog entity.
type CodexResponseLogDelete struct {
	config
	hooks    []Hook
	mutation *CodexResponseLogMutation
}

// Where appends a list predicates to the CodexResponseLogDelete builder.
func (_d *CodexResponseLogDelete) Where(ps ...predicate.CodexResponseLog) *CodexResponseLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CodexResponseLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CodexResponseLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CodexResponseLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(codexresponselog.Table, sqlgraph.NewFieldSpec(codexresponselog.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CodexResponseLogDeleteOne is the builder for deleting a single CodexResponseLog entity.
type CodexResponseLogDeleteOne struct {
	_d *CodexResponseLogDelete
}

// Where appends a list predicates to the CodexResponseLogDelete builder.
func (_d *CodexResponseLogDeleteOne) Where(ps ...predicate.CodexResponseLog) *CodexResponseLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CodexResponseLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{codexresponselog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CodexResponseLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
