// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"myapi/internal/ent/holidayday"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// HolidayDay is the model entity for the HolidayDay schema.
type HolidayDay struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Date holds the value of the "date" field.
	Date string `json:"date,omitempty"`
	// IsOffDay holds the value of the "is_off_day" field.
	IsOffDay     bool `json:"is_off_day,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*HolidayDay) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case holidayday.FieldIsOffDay:
			values[i] = new(sql.NullBool)
		case holidayday.FieldID:
			values[i] = new(sql.NullInt64)
		case holidayday.FieldName, holidayday.FieldDate:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the HolidayDay fields.
func (_m *HolidayDay) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case holidayday.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case holidayday.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case holidayday.FieldDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				_m.Date = value.String
			}
		case holidayday.FieldIsOffDay:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_off_day", values[i])
			} else if value.Valid {
				_m.IsOffDay = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the HolidayDay.
// This includes values selected through modifiers, order, etc.
func (_m *HolidayDay) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this HolidayDay.
// Note that you need to call HolidayDay.Unwrap() before calling this method if this HolidayDay
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *HolidayDay) Update() *HolidayDayUpdateOne {
	return NewHolidayDayClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the HolidayDay entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *HolidayDay) Unwrap() *HolidayDay {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: HolidayDay is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *HolidayDay) String() string {
	var builder strings.Builder
	builder.WriteString("HolidayDay(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("date=")
	builder.WriteString(_m.Date)
	builder.WriteString(", ")
	builder.WriteString("is_off_day=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsOffDay))
	builder.WriteByte(')')
	return builder.String()
}

// HolidayDays is a parsable slice of HolidayDay.
type HolidayDays []*HolidayDay
