// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"myapi/internal/ent/holidayday"
	"myapi/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HolidayDayUpdate is the builder for updating HolidayDay entities.
type HolidayDayUpdate struct {
	config
	hooks    []Hook
	mutation *HolidayDayMutation
}

// Where appends a list predicates to the HolidayDayUpdate builder.
func (_u *HolidayDayUpdate) Where(ps ...predicate.HolidayDay) *HolidayDayUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *HolidayDayUpdate) SetName(v string) *HolidayDayUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HolidayDayUpdate) SetNillableName(v *string) *HolidayDayUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDate sets the "date" field.
func (_u *HolidayDayUpdate) SetDate(v string) *HolidayDayUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *HolidayDayUpdate) SetNillableDate(v *string) *HolidayDayUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetIsOffDay sets the "is_off_day" field.
func (_u *HolidayDayUpdate) SetIsOffDay(v bool) *HolidayDayUpdate {
	_u.mutation.SetIsOffDay(v)
	return _u
}

// SetNillableIsOffDay sets the "is_off_day" field if the given value is not nil.
func (_u *HolidayDayUpdate) SetNillableIsOffDay(v *bool) *HolidayDayUpdate {
	if v != nil {
		_u.SetIsOffDay(*v)
	}
	return _u
}

// Mutation returns the HolidayDayMutation object of the builder.
func (_u *HolidayDayUpdate) Mutation() *HolidayDayMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HolidayDayUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HolidayDayUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HolidayDayUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HolidayDayUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *HolidayDayUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(holidayday.Table, holidayday.Columns, sqlgraph.NewFieldSpec(holidayday.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(holidayday.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(holidayday.FieldDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsOffDay(); ok {
		_spec.SetField(holidayday.FieldIsOffDay, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{holidayday.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HolidayDayUpdateOne is the builder for updating a single HolidayDay entity.
type HolidayDayUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HolidayDayMutation
}

// SetName sets the "name" field.
func (_u *HolidayDayUpdateOne) SetName(v string) *HolidayDayUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *HolidayDayUpdateOne) SetNillableName(v *string) *HolidayDayUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDate sets the "date" field.
func (_u *HolidayDayUpdateOne) SetDate(v string) *HolidayDayUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *HolidayDayUpdateOne) SetNillableDate(v *string) *HolidayDayUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetIsOffDay sets the "is_off_day" field.
func (_u *HolidayDayUpdateOne) SetIsOffDay(v bool) *HolidayDayUpdateOne {
	_u.mutation.SetIsOffDay(v)
	return _u
}

// SetNillableIsOffDay sets the "is_off_day" field if the given value is not nil.
func (_u *HolidayDayUpdateOne) SetNillableIsOffDay(v *bool) *HolidayDayUpdateOne {
	if v != nil {
		_u.SetIsOffDay(*v)
	}
	return _u
}

// Mutation returns the HolidayDayMutation object of the builder.
func (_u *HolidayDayUpdateOne) Mutation() *HolidayDayMutation {
	return _u.mutation
}

// Where appends a list predicates to the HolidayDayUpdate builder.
func (_u *HolidayDayUpdateOne) Where(ps ...predicate.HolidayDay) *HolidayDayUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HolidayDayUpdateOne) Select(field string, fields ...string) *HolidayDayUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated HolidayDay entity.
func (_u *HolidayDayUpdateOne) Save(ctx context.Context) (*HolidayDay, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HolidayDayUpdateOne) SaveX(ctx context.Context) *HolidayDay {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HolidayDayUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HolidayDayUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *HolidayDayUpdateOne) sqlSave(ctx context.Context) (_node *HolidayDay, err error) {
	_spec := sqlgraph.NewUpdateSpec(holidayday.Table, holidayday.Columns, sqlgraph.NewFieldSpec(holidayday.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "HolidayDay.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, holidayday.FieldID)
		for _, f := range fields {
			if !holidayday.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != holidayday.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(holidayday.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(holidayday.FieldDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsOffDay(); ok {
		_spec.SetField(holidayday.FieldIsOffDay, field.TypeBool, value)
	}
	_node = &HolidayDay{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{holidayday.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
