// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"myapi/internal/ent/holidayday"
	"myapi/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HolidayDayDelete is the builder for deleting a HolidayDay entity.
type HolidayDayDelete struct {
	config
	hooks    []Hook
	mutation *HolidayDayMutation
}

// Where appends a list predicates to the HolidayDayDelete builder.
func (_d *HolidayDayDelete) Where(ps ...predicate.HolidayDay) *HolidayDayDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *HolidayDayDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *HolidayDayDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *HolidayDayDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(holidayday.Table, sqlgraph.NewFieldSpec(holidayday.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// HolidayDayDeleteOne is the builder for deleting a single HolidayDay entity.
type HolidayDayDeleteOne struct {
	_d *HolidayDayDelete
}

// Where appends a list predicates to the HolidayDayDelete builder.
func (_d *HolidayDayDeleteOne) Where(ps ...predicate.HolidayDay) *HolidayDayDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *HolidayDayDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{holidayday.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *HolidayDayDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
