// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"myapi/internal/ent/holidayday"
	"myapi/internal/ent/predicate"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeHolidayDay = "HolidayDay"
)

// HolidayDayMutation represents an operation that mutates the HolidayDay nodes in the graph.
type HolidayDayMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	date          *string
	is_off_day    *bool
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*HolidayDay, error)
	predicates    []predicate.HolidayDay
}

var _ ent.Mutation = (*HolidayDayMutation)(nil)

// holidaydayOption allows management of the mutation configuration using functional options.
type holidaydayOption func(*HolidayDayMutation)

// newHolidayDayMutation creates new mutation for the HolidayDay entity.
func newHolidayDayMutation(c config, op Op, opts ...holidaydayOption) *HolidayDayMutation {
	m := &HolidayDayMutation{
		config:        c,
		op:            op,
		typ:           TypeHolidayDay,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withHolidayDayID sets the ID field of the mutation.
func withHolidayDayID(id int) holidaydayOption {
	return func(m *HolidayDayMutation) {
		var (
			err   error
			once  sync.Once
			value *HolidayDay
		)
		m.oldValue = func(ctx context.Context) (*HolidayDay, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().HolidayDay.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withHolidayDay sets the old HolidayDay of the mutation.
func withHolidayDay(node *HolidayDay) holidaydayOption {
	return func(m *HolidayDayMutation) {
		m.oldValue = func(context.Context) (*HolidayDay, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m HolidayDayMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m HolidayDayMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *HolidayDayMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *HolidayDayMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().HolidayDay.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *HolidayDayMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *HolidayDayMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the HolidayDay entity.
// If the HolidayDay object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HolidayDayMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *HolidayDayMutation) ResetName() {
	m.name = nil
}

// SetDate sets the "date" field.
func (m *HolidayDayMutation) SetDate(s string) {
	m.date = &s
}

// Date returns the value of the "date" field in the mutation.
func (m *HolidayDayMutation) Date() (r string, exists bool) {
	v := m.date
	if v == nil {
		return
	}
	return *v, true
}

// OldDate returns the old "date" field's value of the HolidayDay entity.
// If the HolidayDay object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HolidayDayMutation) OldDate(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDate: %w", err)
	}
	return oldValue.Date, nil
}

// ResetDate resets all changes to the "date" field.
func (m *HolidayDayMutation) ResetDate() {
	m.date = nil
}

// SetIsOffDay sets the "is_off_day" field.
func (m *HolidayDayMutation) SetIsOffDay(b bool) {
	m.is_off_day = &b
}

// IsOffDay returns the value of the "is_off_day" field in the mutation.
func (m *HolidayDayMutation) IsOffDay() (r bool, exists bool) {
	v := m.is_off_day
	if v == nil {
		return
	}
	return *v, true
}

// OldIsOffDay returns the old "is_off_day" field's value of the HolidayDay entity.
// If the HolidayDay object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *HolidayDayMutation) OldIsOffDay(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIsOffDay is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIsOffDay requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIsOffDay: %w", err)
	}
	return oldValue.IsOffDay, nil
}

// ResetIsOffDay resets all changes to the "is_off_day" field.
func (m *HolidayDayMutation) ResetIsOffDay() {
	m.is_off_day = nil
}

// Where appends a list predicates to the HolidayDayMutation builder.
func (m *HolidayDayMutation) Where(ps ...predicate.HolidayDay) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the HolidayDayMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *HolidayDayMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.HolidayDay, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *HolidayDayMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *HolidayDayMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (HolidayDay).
func (m *HolidayDayMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *HolidayDayMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.name != nil {
		fields = append(fields, holidayday.FieldName)
	}
	if m.date != nil {
		fields = append(fields, holidayday.FieldDate)
	}
	if m.is_off_day != nil {
		fields = append(fields, holidayday.FieldIsOffDay)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *HolidayDayMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case holidayday.FieldName:
		return m.Name()
	case holidayday.FieldDate:
		return m.Date()
	case holidayday.FieldIsOffDay:
		return m.IsOffDay()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *HolidayDayMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case holidayday.FieldName:
		return m.OldName(ctx)
	case holidayday.FieldDate:
		return m.OldDate(ctx)
	case holidayday.FieldIsOffDay:
		return m.OldIsOffDay(ctx)
	}
	return nil, fmt.Errorf("unknown HolidayDay field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HolidayDayMutation) SetField(name string, value ent.Value) error {
	switch name {
	case holidayday.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case holidayday.FieldDate:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDate(v)
		return nil
	case holidayday.FieldIsOffDay:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIsOffDay(v)
		return nil
	}
	return fmt.Errorf("unknown HolidayDay field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *HolidayDayMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *HolidayDayMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *HolidayDayMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown HolidayDay numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *HolidayDayMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *HolidayDayMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *HolidayDayMutation) ClearField(name string) error {
	return fmt.Errorf("unknown HolidayDay nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *HolidayDayMutation) ResetField(name string) error {
	switch name {
	case holidayday.FieldName:
		m.ResetName()
		return nil
	case holidayday.FieldDate:
		m.ResetDate()
		return nil
	case holidayday.FieldIsOffDay:
		m.ResetIsOffDay()
		return nil
	}
	return fmt.Errorf("unknown HolidayDay field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *HolidayDayMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *HolidayDayMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *HolidayDayMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *HolidayDayMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *HolidayDayMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *HolidayDayMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *HolidayDayMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown HolidayDay unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *HolidayDayMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown HolidayDay edge %s", name)
}
