// Code generated by ent, DO NOT EDIT.

package holidayday

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the holidayday type in the database.
	Label = "holiday_day"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDate holds the string denoting the date field in the database.
	FieldDate = "date"
	// FieldIsOffDay holds the string denoting the is_off_day field in the database.
	FieldIsOffDay = "is_off_day"
	// Table holds the table name of the holidayday in the database.
	Table = "holiday_days"
)

// Columns holds all SQL columns for holidayday fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDate,
	FieldIsOffDay,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the HolidayDay queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDate orders the results by the date field.
func ByDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDate, opts...).ToFunc()
}

// ByIsOffDay orders the results by the is_off_day field.
func ByIsOffDay(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsOffDay, opts...).ToFunc()
}
