// Code generated by ent, DO NOT EDIT.

package holidayday

import (
	"myapi/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldEQ(FieldName, v))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldEQ(FieldDate, v))
}

// IsOffDay applies equality check predicate on the "is_off_day" field. It's identical to IsOffDayEQ.
func IsOffDay(v bool) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldEQ(FieldIsOffDay, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldContainsFold(FieldName, v))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldLTE(FieldDate, v))
}

// DateContains applies the Contains predicate on the "date" field.
func DateContains(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldContains(FieldDate, v))
}

// DateHasPrefix applies the HasPrefix predicate on the "date" field.
func DateHasPrefix(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldHasPrefix(FieldDate, v))
}

// DateHasSuffix applies the HasSuffix predicate on the "date" field.
func DateHasSuffix(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldHasSuffix(FieldDate, v))
}

// DateEqualFold applies the EqualFold predicate on the "date" field.
func DateEqualFold(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldEqualFold(FieldDate, v))
}

// DateContainsFold applies the ContainsFold predicate on the "date" field.
func DateContainsFold(v string) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldContainsFold(FieldDate, v))
}

// IsOffDayEQ applies the EQ predicate on the "is_off_day" field.
func IsOffDayEQ(v bool) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldEQ(FieldIsOffDay, v))
}

// IsOffDayNEQ applies the NEQ predicate on the "is_off_day" field.
func IsOffDayNEQ(v bool) predicate.HolidayDay {
	return predicate.HolidayDay(sql.FieldNEQ(FieldIsOffDay, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.HolidayDay) predicate.HolidayDay {
	return predicate.HolidayDay(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.HolidayDay) predicate.HolidayDay {
	return predicate.HolidayDay(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.HolidayDay) predicate.HolidayDay {
	return predicate.HolidayDay(sql.NotPredicates(p))
}
