// Code generated by ent, DO NOT EDIT.

package codexoauthsession

import (
	"myapi/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldLTE(FieldID, id))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldEQ(FieldState, v))
}

// CodeVerifier applies equality check predicate on the "code_verifier" field. It's identical to CodeVerifierEQ.
func CodeVerifier(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldEQ(FieldCodeVerifier, v))
}

// CodeChallenge applies equality check predicate on the "code_challenge" field. It's identical to CodeChallengeEQ.
func CodeChallenge(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldEQ(FieldCodeChallenge, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldEQ(FieldCreatedAt, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldContainsFold(FieldState, v))
}

// CodeVerifierEQ applies the EQ predicate on the "code_verifier" field.
func CodeVerifierEQ(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldEQ(FieldCodeVerifier, v))
}

// CodeVerifierNEQ applies the NEQ predicate on the "code_verifier" field.
func CodeVerifierNEQ(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldNEQ(FieldCodeVerifier, v))
}

// CodeVerifierIn applies the In predicate on the "code_verifier" field.
func CodeVerifierIn(vs ...string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldIn(FieldCodeVerifier, vs...))
}

// CodeVerifierNotIn applies the NotIn predicate on the "code_verifier" field.
func CodeVerifierNotIn(vs ...string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldNotIn(FieldCodeVerifier, vs...))
}

// CodeVerifierGT applies the GT predicate on the "code_verifier" field.
func CodeVerifierGT(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldGT(FieldCodeVerifier, v))
}

// CodeVerifierGTE applies the GTE predicate on the "code_verifier" field.
func CodeVerifierGTE(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldGTE(FieldCodeVerifier, v))
}

// CodeVerifierLT applies the LT predicate on the "code_verifier" field.
func CodeVerifierLT(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldLT(FieldCodeVerifier, v))
}

// CodeVerifierLTE applies the LTE predicate on the "code_verifier" field.
func CodeVerifierLTE(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldLTE(FieldCodeVerifier, v))
}

// CodeVerifierContains applies the Contains predicate on the "code_verifier" field.
func CodeVerifierContains(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldContains(FieldCodeVerifier, v))
}

// CodeVerifierHasPrefix applies the HasPrefix predicate on the "code_verifier" field.
func CodeVerifierHasPrefix(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldHasPrefix(FieldCodeVerifier, v))
}

// CodeVerifierHasSuffix applies the HasSuffix predicate on the "code_verifier" field.
func CodeVerifierHasSuffix(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldHasSuffix(FieldCodeVerifier, v))
}

// CodeVerifierEqualFold applies the EqualFold predicate on the "code_verifier" field.
func CodeVerifierEqualFold(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldEqualFold(FieldCodeVerifier, v))
}

// CodeVerifierContainsFold applies the ContainsFold predicate on the "code_verifier" field.
func CodeVerifierContainsFold(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldContainsFold(FieldCodeVerifier, v))
}

// CodeChallengeEQ applies the EQ predicate on the "code_challenge" field.
func CodeChallengeEQ(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldEQ(FieldCodeChallenge, v))
}

// CodeChallengeNEQ applies the NEQ predicate on the "code_challenge" field.
func CodeChallengeNEQ(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldNEQ(FieldCodeChallenge, v))
}

// CodeChallengeIn applies the In predicate on the "code_challenge" field.
func CodeChallengeIn(vs ...string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldIn(FieldCodeChallenge, vs...))
}

// CodeChallengeNotIn applies the NotIn predicate on the "code_challenge" field.
func CodeChallengeNotIn(vs ...string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldNotIn(FieldCodeChallenge, vs...))
}

// CodeChallengeGT applies the GT predicate on the "code_challenge" field.
func CodeChallengeGT(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldGT(FieldCodeChallenge, v))
}

// CodeChallengeGTE applies the GTE predicate on the "code_challenge" field.
func CodeChallengeGTE(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldGTE(FieldCodeChallenge, v))
}

// CodeChallengeLT applies the LT predicate on the "code_challenge" field.
func CodeChallengeLT(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldLT(FieldCodeChallenge, v))
}

// CodeChallengeLTE applies the LTE predicate on the "code_challenge" field.
func CodeChallengeLTE(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldLTE(FieldCodeChallenge, v))
}

// CodeChallengeContains applies the Contains predicate on the "code_challenge" field.
func CodeChallengeContains(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldContains(FieldCodeChallenge, v))
}

// CodeChallengeHasPrefix applies the HasPrefix predicate on the "code_challenge" field.
func CodeChallengeHasPrefix(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldHasPrefix(FieldCodeChallenge, v))
}

// CodeChallengeHasSuffix applies the HasSuffix predicate on the "code_challenge" field.
func CodeChallengeHasSuffix(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldHasSuffix(FieldCodeChallenge, v))
}

// CodeChallengeEqualFold applies the EqualFold predicate on the "code_challenge" field.
func CodeChallengeEqualFold(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldEqualFold(FieldCodeChallenge, v))
}

// CodeChallengeContainsFold applies the ContainsFold predicate on the "code_challenge" field.
func CodeChallengeContainsFold(v string) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldContainsFold(FieldCodeChallenge, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CodexOAuthSession) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CodexOAuthSession) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CodexOAuthSession) predicate.CodexOAuthSession {
	return predicate.CodexOAuthSession(sql.NotPredicates(p))
}
