// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"
	"time"
)

const clearReadingProgress = `-- name: ClearReadingProgress :exec
DELETE FROM eh_reading_progress WHERE user_id = $1
`

func (q *Queries) ClearReadingProgress(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, clearReadingProgress, userID)
	return err
}

const deleteEhCredential = `-- name: DeleteEhCredential :exec
DELETE FROM eh_credentials WHERE user_id = $1
`

func (q *Queries) DeleteEhCredential(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteEhCredential, userID)
	return err
}

const deleteReadingProgress = `-- name: DeleteReadingProgress :exec
DELETE FROM eh_reading_progress WHERE user_id = $1 AND gid = $2
`

type DeleteReadingProgressParams struct {
	UserID int64
	Gid    int64
}

func (q *Queries) DeleteReadingProgress(ctx context.Context, arg DeleteReadingProgressParams) error {
	_, err := q.db.Exec(ctx, deleteReadingProgress, arg.UserID, arg.Gid)
	return err
}

const getEhCredential = `-- name: GetEhCredential :one
SELECT member_id, cookie, has_ex_access FROM eh_credentials WHERE user_id = $1
`

type GetEhCredentialRow struct {
	MemberID    string
	Cookie      string
	HasExAccess bool
}

func (q *Queries) GetEhCredential(ctx context.Context, userID int64) (GetEhCredentialRow, error) {
	row := q.db.QueryRow(ctx, getEhCredential, userID)
	var i GetEhCredentialRow
	err := row.Scan(&i.MemberID, &i.Cookie, &i.HasExAccess)
	return i, err
}

const getEhPreferences = `-- name: GetEhPreferences :one
SELECT categories, reader_interval FROM eh_preferences WHERE user_id = $1
`

type GetEhPreferencesRow struct {
	Categories     []string
	ReaderInterval int32
}

func (q *Queries) GetEhPreferences(ctx context.Context, userID int64) (GetEhPreferencesRow, error) {
	row := q.db.QueryRow(ctx, getEhPreferences, userID)
	var i GetEhPreferencesRow
	err := row.Scan(&i.Categories, &i.ReaderInterval)
	return i, err
}

const getEhSearchHistory = `-- name: GetEhSearchHistory :one
SELECT search_history FROM eh_preferences WHERE user_id = $1
`

func (q *Queries) GetEhSearchHistory(ctx context.Context, userID int64) ([]string, error) {
	row := q.db.QueryRow(ctx, getEhSearchHistory, userID)
	var search_history []string
	err := row.Scan(&search_history)
	return search_history, err
}

const getReadingProgress = `-- name: GetReadingProgress :one
SELECT page FROM eh_reading_progress WHERE user_id = $1 AND gid = $2
`

type GetReadingProgressParams struct {
	UserID int64
	Gid    int64
}

func (q *Queries) GetReadingProgress(ctx context.Context, arg GetReadingProgressParams) (int32, error) {
	row := q.db.QueryRow(ctx, getReadingProgress, arg.UserID, arg.Gid)
	var page int32
	err := row.Scan(&page)
	return page, err
}

const listReadingHistory = `-- name: ListReadingHistory :many
SELECT gid, token, page, updated_at FROM eh_reading_progress
WHERE user_id = $1
  AND (NOT $2::boolean OR (updated_at, gid) < ($3::timestamptz, $4::bigint))
ORDER BY updated_at DESC, gid DESC
LIMIT $5
`

type ListReadingHistoryParams struct {
	UserID    int64
	HasCursor bool
	BeforeAt  time.Time
	BeforeGid int64
	PageLimit int32
}

type ListReadingHistoryRow struct {
	Gid       int64
	Token     string
	Page      int32
	UpdatedAt time.Time
}

// 阅读历史与进度共用一张表；时间相同时用 gid 保证分页顺序稳定。
func (q *Queries) ListReadingHistory(ctx context.Context, arg ListReadingHistoryParams) ([]ListReadingHistoryRow, error) {
	rows, err := q.db.Query(ctx, listReadingHistory,
		arg.UserID,
		arg.HasCursor,
		arg.BeforeAt,
		arg.BeforeGid,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReadingHistoryRow{}
	for rows.Next() {
		var i ListReadingHistoryRow
		if err := rows.Scan(
			&i.Gid,
			&i.Token,
			&i.Page,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveEhPreferences = `-- name: SaveEhPreferences :exec
INSERT INTO eh_preferences (user_id, categories, reader_interval, created_at, updated_at)
VALUES ($1, $2, $3, now(), now())
ON CONFLICT (user_id) DO UPDATE
SET categories = excluded.categories, reader_interval = excluded.reader_interval, updated_at = now()
`

type SaveEhPreferencesParams struct {
	UserID         int64
	Categories     []string
	ReaderInterval int32
}

// 整份覆盖前端推上来的那一份，不在这里算增量。
func (q *Queries) SaveEhPreferences(ctx context.Context, arg SaveEhPreferencesParams) error {
	_, err := q.db.Exec(ctx, saveEhPreferences, arg.UserID, arg.Categories, arg.ReaderInterval)
	return err
}

const saveEhSearchHistory = `-- name: SaveEhSearchHistory :exec
INSERT INTO eh_preferences (user_id, search_history, created_at, updated_at)
VALUES ($1, $2, now(), now())
ON CONFLICT (user_id) DO UPDATE
SET search_history = excluded.search_history, updated_at = now()
`

type SaveEhSearchHistoryParams struct {
	UserID        int64
	SearchHistory []string
}

// 同样整份覆盖；顺序、去重、留几条都是前端定好的。
func (q *Queries) SaveEhSearchHistory(ctx context.Context, arg SaveEhSearchHistoryParams) error {
	_, err := q.db.Exec(ctx, saveEhSearchHistory, arg.UserID, arg.SearchHistory)
	return err
}

const upsertEhCredential = `-- name: UpsertEhCredential :exec
INSERT INTO eh_credentials (user_id, member_id, cookie, has_ex_access, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
ON CONFLICT (user_id) DO UPDATE
SET member_id = excluded.member_id,
    cookie = excluded.cookie,
    has_ex_access = excluded.has_ex_access,
    updated_at = now()
`

type UpsertEhCredentialParams struct {
	UserID      int64
	MemberID    string
	Cookie      string
	HasExAccess bool
}

func (q *Queries) UpsertEhCredential(ctx context.Context, arg UpsertEhCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertEhCredential,
		arg.UserID,
		arg.MemberID,
		arg.Cookie,
		arg.HasExAccess,
	)
	return err
}

const upsertReadingProgress = `-- name: UpsertReadingProgress :exec
INSERT INTO eh_reading_progress (user_id, gid, token, page, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
ON CONFLICT (user_id, gid) DO UPDATE
SET token = excluded.token,
    page = excluded.page,
    updated_at = now()
`

type UpsertReadingProgressParams struct {
	UserID int64
	Gid    int64
	Token  string
	Page   int32
}

func (q *Queries) UpsertReadingProgress(ctx context.Context, arg UpsertReadingProgressParams) error {
	_, err := q.db.Exec(ctx, upsertReadingProgress,
		arg.UserID,
		arg.Gid,
		arg.Token,
		arg.Page,
	)
	return err
}
