// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// HolidayDay is the predicate function for holidayday builders.
type HolidayDay func(*sql.Selector)
