-- 表结构的唯一真相。
--
-- 进程不碰 DDL：建表、改列、加索引都由人工上库执行（Spring Boot 只对内嵌数据库自动执行 classpath 上的 schema.sql，
-- PostgreSQL 不会被自动执行；测试里的 Mapper 测试会显式跑一遍）。语句写成 IF NOT EXISTS 的幂等形式，重跑一遍不会报错。
--
-- 建表约定：
--   * id / created_at / updated_at 三列一张不少，id 用 SQL 标准的 identity 而不是 serial；
--   * 两个时间列没有 default，值由 Mapper XML 里的 now() 显式写入——
--     新写一条 INSERT 时漏掉它们会直接报 NOT NULL 违例，而不是悄悄落一个别处填的时间；
--   * 业务上的唯一性用 unique 索引表达，不占主键位置，它同时是各自 upsert 的冲突目标。

CREATE TABLE IF NOT EXISTS users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT        NOT NULL,
    password_hash TEXT        NOT NULL,
    created_at    timestamptz NOT NULL,
    updated_at    timestamptz NOT NULL
);

-- 用户名大小写敏感：Alice 和 alice 是两个账号，登录要求完全一致，所以是建在列上的普通唯一索引。
CREATE UNIQUE INDEX IF NOT EXISTS users_username_key ON users (username);

-- 每个用户绑定的 e 站 Cookie。cookie 列存 JSON 明文，不加密——
-- 注册不开放，库里只有自己人的凭据，为此再上一层加解密不划算。
-- 代价要认清：**这一列等同于 e 站账号本身**，拿到就能登进去，改密码也不影响。
-- 数据库备份、从库、给监控开的只读账号，都要按凭据的标准对待。
--
-- member_id 单独一列，是为了设置页显示「已绑定 xxx」时不必解析 JSON。
CREATE TABLE IF NOT EXISTS eh_credentials
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    member_id     TEXT        NOT NULL,
    cookie        TEXT        NOT NULL,
    has_ex_access BOOLEAN     NOT NULL,
    created_at    timestamptz NOT NULL,
    updated_at    timestamptz NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS eh_credentials_user_id_key ON eh_credentials (user_id);

-- writer / seq 是最后一次写入的上报方（前端的一次页面加载）和它的上报序号。前端不排队、并发地上报，
-- 同一上报方迟到的旧序号不再覆盖；不同上报方之间不比较，照到达顺序覆盖——
-- 换成时间戳也比不了：各设备的时钟对不齐，时钟快的那台会一直压住别的设备的进度。
CREATE TABLE IF NOT EXISTS eh_reading_progress
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    gid        BIGINT      NOT NULL,
    token      TEXT        NOT NULL,
    page       INTEGER     NOT NULL,
    writer     TEXT        NOT NULL,
    seq        INTEGER     NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS eh_reading_progress_user_gid_key ON eh_reading_progress (user_id, gid);
CREATE INDEX IF NOT EXISTS eh_reading_progress_user_recent_idx ON eh_reading_progress (user_id, updated_at DESC, gid DESC);

-- 图集浏览的账号偏好与最近搜索词；各字段独立更新，不整行覆盖其他设备的修改。
CREATE TABLE IF NOT EXISTS eh_preferences
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    categories      TEXT[]      NOT NULL DEFAULT '{}',
    reader_interval INTEGER     NOT NULL DEFAULT 5 CHECK (reader_interval BETWEEN 1 AND 20),
    search_history  TEXT[]      NOT NULL DEFAULT '{}' CHECK (CARDINALITY(search_history) <= 10),
    created_at      timestamptz NOT NULL,
    updated_at      timestamptz NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS eh_preferences_user_id_key ON eh_preferences (user_id);

-- date 列存 YYYY-MM-DD 字符串而不是 date 类型：年份即前缀，删整年靠 LIKE 'YYYY-%'，
-- 进出接口和远程 JSON 也都是这个格式，省掉两头的类型转换。
CREATE TABLE IF NOT EXISTS holiday_days
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT        NOT NULL,
    date       TEXT        NOT NULL,
    is_off_day BOOLEAN     NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

-- 每个日期只有一条安排，按日期查询由此保证最多命中一行。
CREATE UNIQUE INDEX IF NOT EXISTS holiday_days_date_key ON holiday_days (date);
