// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"myapi/internal/app"
	"myapi/internal/auth"
	"myapi/internal/config"
	"myapi/internal/eh"
	"myapi/internal/holiday"
	"myapi/internal/store"
)

import (
	_ "time/tzdata"
)

// Injectors from wire.go:

// initApplication 从零装出整个应用：读配置、建日志器、建连接池、把各层 new 出来。
//
// 返回的 cleanup 串起了图里所有 provider 的清理动作（目前只有连接池），
// 中途哪一步失败，已经建好的部分也会被清掉。
func initApplication(ctx context.Context) (*application, func(), error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, nil, err
	}
	string2 := configConfig.StaticDir
	logger := provideLogger(configConfig)
	pool, cleanup, err := provideDatabase(ctx, configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	queries := store.New(pool)
	remoteClient := holiday.NewRemoteClient()
	service := holiday.NewService(pool, queries, remoteClient)
	handler := holiday.NewHandler(service)
	authService := provideAuthService(queries, configConfig)
	tokens := provideTokens(configConfig)
	authHandler := auth.NewHandler(authService, tokens)
	client := provideEhClient(configConfig)
	credentialStore := eh.NewCredentialStore(queries, client)
	imageLocator := eh.NewImageLocator(client)
	attachmentSigner := provideAttachmentSigner(configConfig)
	ehService := eh.NewService(queries, client, credentialStore, imageLocator, attachmentSigner)
	ehHandler := eh.NewHandler(ehService, tokens)
	httpHandler := app.NewRouter(string2, handler, authHandler, ehHandler)
	mainApplication := &application{
		Config:  configConfig,
		Router:  httpHandler,
		Holiday: service,
	}
	return mainApplication, func() {
		cleanup()
	}, nil
}
